#!/usr/bin/env python3
"""pretags.json 汉化脚本"""
import json
import os
import re
from pathlib import Path

# 使用相对路径
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
SRC = PROJECT_ROOT / 'pretags.json'

# ===== Source映射（已从之前代码合并） =====
SOURCE_MAP = {
    'Granblue_Fantasy': '碧蓝幻想', 'NIKKE': '胜利女神：妮姬',
    'Fate': 'Fate系列', 'Hololive': 'Hololive', 'FLCL': 'FLCL',
    'Project_Moon': 'Project Moon', 'Love_Live': 'LoveLive!',
    'Vocaloid': 'VOCALOID', 'indie_virtual_youtuber': '独立虚拟主播',
    'tokyo_afterschool_summoners': '东京放学后召唤师', "queen's_blade": '女王之刃',
    'senran_kagura': '闪乱神乐', 'last_origin': '最后的起源', 'elsword': '艾尔之光',
    'kamen_rider': '假面骑士', 'warship_girls_r': '战舰少女R', 'apex_legends': 'Apex英雄',
    'apex_传奇': 'Apex英雄', 'marvel': '漫威', 'nanashi_inc.': 'nanashi inc.',
    'vspo!': 'VSPO!', 'omori': 'OMORI', 'dc_漫画': 'DC漫画', 'dc_comics': 'DC漫画',
    'skullgirls': '骷髅女孩', 'axis_powers_hetalia': '黑塔利亚', 'vshojo': 'VShojo',
    'Vshojo': 'VShojo', 'splatoon_series': '喷射战士', 'assault_lily': '突击莉莉',
    'pretty_series': 'Pretty系列', 're:stage!': 'Re:Stage!', 'os-tan': 'OS娘',
    'elden_ring': '艾尔登法环', 'puyopuyo': '噗哟噗哟', 'disgaea': '魔界战记',
    'monster_girl_encyclopedia': '魔物娘图鉴', 'Avatar:_The_Last_Airbender': '降世神通',
    'phantasy_star': '梦幻之星', 'world_witches_series': '强袭魔女系列',
    'mahou_sensei_negima!': '魔法老师涅吉', '舰队Collection': '舰队Collection',
    'dungeon_meshi': '迷宫饭', 'blue_lock': '蓝色监狱', 'black_clover': '黑色五叶草',
    'high_school_dxd': '高校DxD', 'one-punch_man': '一拳超人',
    'no_game_no_life': '游戏人生', 're:creators': 'Re:Creators',
    'goblin_slayer!': '哥布林杀手', 'berserk': '剑风传奇',
    'helltaker': '地狱把妹王', 'rwby': 'RWBY', 'hellsing': '皇家国教骑士团',
    'koihime_musou': '恋姬无双', 'monster_musume_no_iru_nichijou': '魔物娘的相伴日常',
    'panty_&_stocking_with_garterbelt': '吊带袜天使', 'nekopara': '猫娘乐园',
    'saki': '天才麻将少女', 'shirobako': '白箱', 'summertime_render': '夏日重现',
    'tenchi_muyou!': '天地无用', 'to_love-ru': '出包王女', 'tokyo_ghoul': '东京食尸鬼',
    'tsukihime': '月姬', 'twisted_wonderland': '扭曲仙境', 'utawarerumono': '传颂之物',
    'world_trigger': '境界触发者', 'yuru_yuri': '摇曳百合', 'yuyushiki': '悠悠式',
    'zero_no_tsukaima': '零之使魔', 'chuunibyou_demo_koi_ga_shitai!': '中二病也要谈恋爱',
    'darker_than_black': '黑之契约者', 'guilty_crown': '罪恶王冠',
    'mononoke_hime': '幽灵公主', 'howl_no_ugoku_shiro': '哈尔的移动城堡',
    'kaze_no_tani_no_nausicaa': '风之谷', 'tenkuu_no_shiro_laputa': '天空之城',
    'majo_no_takkyuubin': '魔女宅急便', 'sen_to_chihiro_no_kamikakushi': '千与千寻',
    'sekiro:_shadows_die_twice': '只狼', 'undertale': '传说之下', 'deltarune': 'Deltarune',
    'hollow_knight': '空洞骑士', 'stardew_valley': '星露谷物语',
    'dark_souls_series': '黑暗之魂', 'bloodborne': '血源诅咒',
    'devil_may_cry_series': '鬼泣', 'resident_evil': '生化危机',
    'kingdom_hearts': '王国之心', 'hades_series': '哈迪斯', 'valorant': '无畏契约',
    'armored_core': '装甲核心', "baldur's_gate": '博德之门', 'bayonetta_series': '猎天使魔女',
    'dead_or_alive': '死或生', 'dead_space': '死亡空间', 'detroit:_become_human': '底特律：变人',
    'disco_elysium': '极乐迪斯科', 'dota_series': 'DOTA', "dragon's_crown": '龙之皇冠',
    'dragalia_lost': '失落的龙约', 'epic_seven': '第七史诗', 'fatal_fury': '饿狼传说',
    'fear_&_hunger': '恐惧与饥饿', 'final_fight': '快打旋风', 'god_eater': '噬神者',
    'god_of_war': '战神', 'grandia': '格兰蒂亚', 'gravity_daze': '重力异想世界',
    'halo_series': '光环', 'horizon_zero_dawn': '地平线：零之曙光', 'ico': 'ICO',
    'journey': '风之旅人', 'justice_gakuen': '正义学园', 'kid_icarus': '新·光神话',
    'library_of_ruina': '废墟图书馆', 'limbus_company': '边狱公司',
    'lollipop_chainsaw': '电锯甜心', 'mass_effect_series': '质量效应',
    'metroid': '密特罗德', 'mortal_kombat_series': '真人快打', 'mother_2': '地球冒险2',
    'ninja_gaiden': '忍者龙剑传', 'octopath_traveler': '八方旅人',
    'palworld': '幻兽帕鲁', 'phantom_brave': '灵武战记', 'portal_series': '传送门',
    'rance_series': '兰斯系列', 'samurai_spirits': '侍魂', 'silent_hill_series': '寂静岭',
    'sinoalice': '死亡爱丽丝', 'soulcalibur': '灵魂能力', 'star_fox': '星际火狐',
    'star_wars': '星球大战', 'starcraft': '星际争霸', 'stellar_blade': '星刃',
    'super_robot_wars': '超级机器人大战', 'team_fortress_2': '军团要塞2',
    'the_last_of_us_series': '最后生还者', 'the_witcher_series': '巫师',
    'titanfall_series': '泰坦陨落', 'unicorn_overlord': '圣兽之王',
    'VA-11_HALL-A': 'VA-11 HALL-A', 'valkyrie_profile_series': '北欧女神',
    'virtua_fighter': 'VR战士', 'xenogears': '异度装甲', 'xenosaga': '异度传说', 'ys': '伊苏',
    'zone_of_the_enders': '终极地带', 'c_control': '[C] THE MONEY OF SOUL',
    'c_控制': '[C] THE MONEY OF SOUL', 'lupin_iii': '鲁邦三世',
    'the_elder_scrolls': '上古卷轴', 'metal_gear_series': '合金装备',
    'bravely_default_series': '勇气默示录', "assassin's_creed_series": '刺客信条',
    'call_of_duty': '使命召唤', 'castlevania_series': '恶魔城', 'catherine_game': '凯瑟琳',
    'celeste_video_game': '蔚蓝', 'chrono_cross': '穿越时空', 'chrono_trigger': '时空之轮',
    'code_vein': '噬血代码', 'cookie_run': '跑跑姜饼人', 'counter:side': '异界事务所',
    'cyberpunk_series': '赛博朋克', 'dead_stranding': '死亡搁浅',
    'fallout_series': '辐射', 'guilty_gear': '罪恶装备', 'helldivers_series': '绝地潜兵',
    'majo_no_tabitabi': '魔女之旅', 'spy_x_family': '间谍过家家',
    'sousou_no_frieren': '葬送的芙莉莲', 'tate_no_yuusha_no_nariagari': '盾之勇者成名录',
    'youkoso_jitsuryoku_shijou_shugi_no_kyoushitsu_e': '欢迎来到实力至上主义的教室',
    'persona_series': '女神异闻录', 'shin_megami_tensei': '真女神转生',
    'dead_by_daylight': '黎明杀机', 'identity_v': '第五人格',
    'project_sekai': '世界计划', 'bang_dream!': 'BanG Dream!', 'd4dj': 'D4DJ',
    'hypnosis_mic': '催眠麦克风', 'idolish7': 'IDOLiSH7',
    'alchemy_stars': '白夜极光', 'dragon_quest': '勇者斗恶龙',
    'final_fantasy': '最终幻想', 'league_of_legends': '英雄联盟',
    'overwatch': '守望先锋', 'super_mario': '超级马力欧',
    'legend_of_zelda': '塞尔达传说', 'xenoblade_chronicles': '异度之刃',
    'tales_of_series': '传说系列', 'fire_emblem': '火焰纹章', 'wild_arms': '荒野兵器',
    'nier_automata': '尼尔：自动人形', 'danganronpa': '弹丸论破',
    'ace_attorney': '逆转裁判', 'animal_crossing': '动物森友会',
    'dead_cells': '死亡细胞', 'minecraft': '我的世界',
    'absolute_duo': '绝对双刃', 'accel_world': '加速世界', 'adventure_time': '探险活宝',
    'aikatsu!': '偶像活动', 'akame_ga_kill!': '斩·赤红之瞳', 'akira_manga': '阿基拉',
    'aldnoah.zero': 'ALDNOAH.ZERO', 'alice_gear_aegis': 'Alice Gear Aegis',
    'alice_in_wonderland': '爱丽丝梦游仙境', 'amagi_brilliant_park': '甘城光辉游乐园',
    'another': '替身', 'ao_no_exorcist': '青之驱魔师', 'aoki_hagane_no_arpeggio': '苍蓝钢铁的琶音',
    'ar_tonelico': '魔塔大陆', 'arc_the_lad': '亚克传承', 'arcaea': 'Arcaea',
    'arcana_heart': '阿鲁卡纳之心', 'ayakashi_triangle': '妖幻三重奏',
    'azumanga_daioh': '阿滋漫画大王', 'azure_striker_gunvolt': '苍蓝雷霆',
    'ben-tou': '便·当', 'bishoujo_senshi_sailor_moon': '美少女战士',
    'black_bullet': '漆黑的子弹', 'blame!': 'BLAME!', 'blend_s': '调教咖啡厅',
    'boku_wa_tomodachi_ga_sukunai': '我的朋友很少',
    'bokutachi_wa_benkyou_ga_dekinai': '我们无法一起学习',
    'bungaku_shoujo': '文学少女', 'busou_shinki': '武装神姬',
    'canaan_series': 'CANAAN', 'chaos;head': 'CHAOS;HEAD',
    'claymore_series': '大剑', 'closers': '封印者', 'comic_girls': '漫画女孩',
    'cross_ange': '天使与龙的轮舞', 'da_capo': '初音岛', 'dagashi_kashi': '粗点心战争',
    'dennou_coil': '电脑线圈', 'dog_days': 'DOG DAYS', 'dororo_tezuka': '多罗罗',
    'el_shaddai': '全能之神', 'endro!': 'ENDRO!', 'engage_kiss': '契约之吻',
    'ergo_proxy': '死亡代理人', 'ever_17': 'Ever17', 'everlasting_summer': '永恒夏日',
    'fairy_fencer_f': '妖精剑士F', 'fantasy_earth': '幻想大陆',
    'flip_flappers': '轻拍翻转小魔女', 'frame_arms_girl': '机甲少女',
    'franken_fran': '疯狂怪医芙兰', 'frozen_disney': '冰雪奇缘',
    'full_moon_wo_sagashite': '寻找满月', 'ga_geijutsuka_art_design_class': 'GA艺术科美术设计班',
    'gabriel_dropout': '珈百璃的堕落', 'gakusen_toshi_asterisk': '学战都市',
    'galaxy_angel': '银河天使', 'gatchaman_crowds': '科学小飞侠Crowds',
    'gegege_no_kitarou': '鬼太郎', 'genshiken': '现视研',
    'getsuyoubi_no_tawawa': '星期一的丰满', 'girl_cafe_gun': '双生视界',
    'girlfriend_kari': '临时女友', 'girlish_number': '少女编号', 'gj-bu': 'GJ部',
    'godzilla_series': '哥斯拉', 'gravity_falls': '怪诞小镇', 'gunslinger_girl': '神枪少女',
    'haibane_renmei': '灰羽联盟', 'haiyore!_nyaruko-san': '潜行吧！奈亚子',
    'hanayamata': '花舞少女', 'happy_sugar_life': 'Happy Sugar Life',
    'hataraku_maou-sama!': '打工吧！魔王大人', 'hataraku_saibou': '工作细胞',
    'hidan_no_aria': '绯弹的亚里亚', 'high_school_fleet': '高校舰队',
    'highschool_of_the_dead': '学园默示录', 'hikaru_no_go': '棋魂',
    'himouto!_umaru-chan': '干物妹！小埋', 'hoshizora_no_memoria': '星空的记忆',
    'hyakka_ryouran_samurai_girls': '百花缭乱', 'hyakko': '白虎', 'ib': 'Ib',
    'ikkitousen': '一骑当千', 'jashin-chan_dropkick': '邪神与厨二病少女',
    'jewelpet_series': '宝石宠物', 'jigokuraku': '地狱乐', 'jormungand_manga': '军火女王',
    'juuni_kokuki': '十二国记', 'k-project': 'K', 'kagerou_project': '阳炎Project',
    'kaibutsu_oujo': '怪物王女', 'kaichou_wa_maid-sama!': '会长是女仆大人',
    'kemurikusa': '烟草', 'kiddy_grade': '银河冒险战记', 'kill_me_baby': '爱杀宝贝',
    'kino_no_tabi': '奇诺之旅', 'kiznaiver': '羁绊者',
    'kore_wa_zombie_desu_ka?': '这个是僵尸吗？', 'koutetsujou_no_kabaneri': '甲铁城的卡巴内瑞',
    'kumo_desu_ga_nani_ka?': '转生成蜘蛛又怎样！', 'kyoukai_no_kanata': '境界的彼方',
    'kyoukaisenjou_no_horizon': '境界线上的地平线', 'last_exile': '最终流放',
    'lotte_no_omocha!': '露蒂的玩具', 'love_hina': '纯情房东俏房客',
    'machikado_mazoku': '街角魔族', 'mahou_shoujo_ikusei_keikaku': '魔法少女育成计划',
    'mahou_shoujo_ni_akogarete': '憧憬成为魔法少女',
    'mahouka_koukou_no_rettousei': '魔法科高校的劣等生',
    'mairimashita!_iruma-kun': '入间同学入魔了！',
    'maji_de_watashi_ni_koi_shinasai!': '认真和我恋爱！', 'maken-ki!': '魔剑姬！',
    'maria-sama_ga_miteru': '圣母在上', 'maria_holic': '玛利亚狂热',
    'masamune-kun_no_revenge': '政宗君的复仇', 'mawaru_penguindrum': '回转企鹅罐',
    'mayo_chiki!': '迷茫管家与懦弱的我', 'mayoi_neko_overrun!': '迷途猫',
    'medaka_box': '最强会长黑神', 'mitsuboshi_colors': '三颗星彩色冒险',
    'moetan': '萌单', 'mononoke': '怪化猫', 'munou_na_nana': '无能的奈奈',
    'musaigen_no_phantom_world': '无彩限的怪灵世界', 'muv-luv': 'Muv-Luv',
    'Muv-Luv': 'Muv-Luv', 'my-hime': '舞-HiME', 'my-otome': '舞-乙HiME',
    'my_little_pony': '小马宝莉', 'new_game!': 'NEW GAME!',
    'nurarihyon_no_mago': '滑头鬼之孙', 'ore_twintail_ni_narimasu': '我，要成为双马尾',
    'ousama_ranking': '国王排名', 'outbreak_company': '萌萌侵略者',
    'pandora_hearts': '潘朵拉之心', 'papa_no_iu_koto_wo_kikinasai!': '要听爸爸的话！',
    'plastic_memories': '可塑性记忆', 'princess_lover': '公主恋人',
    'princess_principal': 'Princess Principal', 'princess_tutu': '彩梦芭蕾',
    'qualidea_code': 'Qualidea Code', 'rewrite': 'Rewrite',
    'rinne_no_lagrange': '轮回的拉格朗日', 'robotics;notes': 'ROBOTICS;NOTES',
    'rokka_no_yuusha': '六花的勇者', 'rosario+vampire': '十字架与吸血鬼',
    'rou-kyuu-bu!': '萝球社！', 'saber_marionette_j': '机械女神J',
    'sakura_quest': '樱花任务', 'sankarea': '散华礼弥', 'saya_no_uta': '沙耶之歌',
    'scryed': '分身战士', 'seikon_no_qwaser': '圣痕炼金士', 'sekirei': '鹡鸰女神',
    'servant_x_service': 'SERVANT×SERVICE', 'shigofumi': '死后文',
    'shimoneta_to_iu_gainen_ga_sonzai_shinai_taikutsu_na_sekai': '没有下流梗概念的无聊世界',
    'shoujo_kageki_revue_starlight': '少女☆歌剧 Revue Starlight',
    '少女歌剧Revue_Starlight': '少女☆歌剧 Revue Starlight',
    'shoujo_shuumatsu_ryokou': '少女终末旅行', 'shugo_chara!': '守护甜心！',
    'sister_princess': '妹妹公主', 'sk8_the_infinity': 'SK∞',
    'slow_start': 'Slow Start', 'sora_no_method': '天体的秩序',
    'sora_no_otoshimono': '天降之物', 'sora_no_woto': '空之音',
    'sora_yori_mo_tooi_basho': '比宇宙更远的地方', 'strike_the_blood': '噬血狂袭',
    'suisei_no_gargantia': '翠星之加尔刚蒂亚', 'tamako_market': '玉子市场',
    'tantei_opera_milky_holmes': '侦探歌剧：少女福尔摩斯', 'tari_tari': 'TARI TARI',
    'tenjou_tenge': '天上天下', 'tonari_no_seki-kun': '上课小动作',
    'tsubasa_chronicle': '翼·年代记', 'tsugumomo': '怪怪守护神',
    'uchuu_patrol_luluco': '宇宙巡警露露子', 'umi_monogatari': '海物语',
    'un-go': 'UN-GO', 'ushinawareta_mirai_wo_motomete': '寻找失去的未来',
    'uta_no_prince-sama': '歌之☆王子殿下', 'vividred_operation': 'Vividred Operation',
    'wakfu': '沃土', 'witch_craft_works': 'Witch Craft Works',
    'working!!': 'WORKING!!', 'yama_no_susume': '向山进发',
    'yofukashi_no_uta': '彻夜之歌', 'tsuritama': '钓球',
    'yosuga_no_sora': '缘之空', 'yotsubato!': '四叶妹妹', 'zoids': '索斯机械兽',
    'among_us': 'Among Us', 'bioshock_series': '生化奇兵', 'bunny_garden': '兔子花园',
    'chaos;child': 'CHAOS;CHILD', 'cult_of_the_lamb': '咩咩启示录',
    'dino_crisis': '恐龙危机', 'drag-on_dragoon': '龙背上的骑兵',
    'dragon_half': '半龙少女', 'dream_c_club': '梦幻俱乐部',
    'druaga_no_tou': '德鲁亚加之塔', 'dumbbell_nan_kilo_moteru?': '流汗吧！健身少女',
    'dungeon_ni_deai_wo_motomeru_no_wa_machigatteiru_darou_ka': '在地下城寻求邂逅是否搞错了什么',
    "eden's_zero": '伊甸星原', "en'en_no_shouboutai": '炎炎消防队',
    "friday_night_funkin'": '周五夜放克', 'gnosia': 'GNOSIA',
    'hai_to_gensou_no_grimgar': '灰与幻想的格林姆迦尔', 'hazbin_hotel': '哈兹宾酒店',
    'helluva_boss': '地狱老板', 'love_and_deepspace': '爱与深空',
    'lord_of_the_mysteries': '诡秘之主', 'lovebrush_chronicles': '绘旅人',
    'luo_xiaohei_zhanji': '罗小黑战记', 'mabinogi': '洛奇',
    'machine-doll_wa_kizutsukanai': '机巧少女不会受伤', 'mahjong_soul': '雀魂',
    'maitetsu': '爱上火车', 'master_detective_archives:_rain_code': '超侦探事件簿 雾雨迷宫',
    'mato_seihei_no_slave': '魔都精兵的奴隶', "mcdonald's": '麦当劳',
    'mermaid_melody_pichi_pichi_pitch': '人鱼的旋律', 'miraculous_ladybug': '奇迹少女',
    'needy_girl_overdose': '主播女孩重度依赖', 'nu_carnival': '新世界狂欢',
    'odin_sphere': '奥丁领域', 'ojamajo_doremi': '小魔女DoReMi',
    "omniscient_reader's_viewpoint": '全知读者视角', 'onmyoji': '阴阳师',
    'oshi_no_ko': '我推的孩子', '推しの子': '我推的孩子',
    'pangya': '魔法飞球', 'paripi_koumei': '派对浪客诸葛孔明',
    'phantom_kingdom': '灵武战记', 'phantom_of_the_kill': '杀戮幻影',
    'project_kv': 'Project KV', 'rainbow_six_siege': '彩虹六号：围攻',
    'ranma_1/2': '乱马½', 'sakura-sou_no_pet_na_kanojo': '樱花庄的宠物女孩',
    'sanrio': '三丽鸥', 'shantae_series': '香缇', 'simoun': 'Simoun',
    'slow_loop': 'SLOW LOOP', 'slime_taoshite_300_nen_shiranai_uchi_ni_level_max_ni_nattemashita': '打了300年的史莱姆',
    'space_channel_5': '太空频道5', 'spice_and_wolf': '狼与香辛料',
    'star_vs_the_forces_of_evil': '星蝶公主', 'steven_universe': '宇宙小子',
    'strawberry_panic!': '惊爆草莓', 'summer_wars': '夏日大作战',
    'summon_night': '召唤之夜', 'suzume_no_tojimari': '铃芽之旅',
    'takt_op.': '宿命回响', 'teenage_mutant_ninja_turtles': '忍者神龟',
    'tenki_no_ko': '天气之子', 'tera_online': 'TERA',
    'the_amazing_digital_circus': '神奇数字马戏团',
    'tiger_&_bunny': 'TIGER & BUNNY', 'tokyo_7th_sisters': '东京第七姐妹',
    'tokyo_mew_mew': '东京猫猫', 'transformers': '变形金刚',
    'youkai_watch': '妖怪手表', 'yume_nisshi': '梦日记',
    'zhu_xian': '诛仙', 'zom_100:_zombie_ni_naru_made_ni_shitai_100_no_koto': '僵尸百分百',
    'zombie_land_saga': '佐贺偶像是传奇', 'yuragisou_no_yuuna-san': '汤摇庄的幽奈同学',
    'juusan_kihei_bouei_ken': '十三机兵防卫圈',
    'Go!_公主光之美少女': 'Go!Princess光之美少女', 'AIR_视觉小说': 'AIR',
    'ARIA（漫画）': '水星领航员', 'F-零': 'F-Zero', '空-null': '空',
    'douluo_dalu': '斗罗大陆', 'doupo_cangqiong': '斗破苍穹',
    '.hack//': '.hack//', '.live': '.live', '11eyes': '11eyes',
    '2.5_jigen_no_ririsa': '2.5次元的诱惑', '7th_dragon': '第七龙神',
    '7th_dragon_series': '第七龙神系列', '9-nine-': '9-nine-',
    'C.C._柠檬': 'C.C.柠檬', 'KRT女孩': 'KRT女孩', 'W·尾巴猫': 'W·尾巴猫',
    'Nitroplus': 'Nitroplus', 'Show_By_Rock!!': 'Show By Rock!!',
    'Monster_Girl_Encyclopedia': '魔物娘图鉴', 'Monster_Girl_Quest': '魔物娘Quest',
    'bilibili': 'B站', 'blackpink': 'BLACKPINK', 'aespa': 'aespa',
    'acfun': 'AcFun', 'a.i._voice': 'AI声音', 'aa_megami-sama': '我的女神',
    'acchi_kocchi': '一起一起这里那里', 'agent_aika': 'AIKa',
    'ai_yori_aoshi': '青出于蓝', 'air_gear': '飞轮少年',
    'akatsuki_no_yona': '晨曦公主', 'akuma_no_riddle': '恶魔之谜',
    'alien_stage': 'Alien Stage', 'all_saints_street': '万圣街', 'amagami': '圣诞之吻',
    'amairo_islenauts': '天色Islenauts', 'animare': 'Animare',
    'ashita_no_nadja': '明日之娜佳', 'baby_princess': 'Baby Princess',
    'bacchikoi!': 'Bacchikoi!', 'bakuman': '爆漫王', 'bakumatsu_rouman': '幕末浪漫',
    'bakuretsu_hunters': '爆裂猎人', 'bakuretsu_tenshi': '爆裂天使',
    "bakusou_kyoudai_let's_&_go!!": '爆走兄弟', 'barbie_franchise': '芭比',
    'battle_spirits': 'Battle Spirits', 'beat_angel_escalayer': '超昂天使',
    'black_cat_series': '黑猫', 'black_jack_series': '怪医黑杰克',
    'blood-c': 'BLOOD-C', 'bobobo-bo_bo-bobo': '鼻毛真拳',
    'boku_dake_ga_inai_machi': '只有我不在的街道', 'boku_no_kanojo_sensei': '我的女友是老师',
    'brave_witches': '无畏魔女', 'breath_of_fire': '龙战士', 'brown_dust_2': '棕色尘埃2',
    'bural_chingu': 'Bural Chingu', 'burn_the_witch': 'BURN THE WITCH',
    'c.c._lemon': 'C.C.Lemon', 'captain_earth': '地球队长',
    'cardfight!!_vanguard': '卡片战斗先导者', 'casshern_series': '再造人卡辛',
    'chikanoko': '鹿乃子乃子', 'chou_shittou_caduceus': '超执刀',
    'choujin_x': '超人X', 'choukou_sennin_haruka': '超昂闪忍遥',
    'chouon_senshi_borgman': '超音战士博格曼', 'coppelion': 'COPPELION',
    'corrector_yui': '网络安琪儿', 'cosmic_break': 'Cosmic Break',
    'crayon_shin-chan': '蜡笔小新', 'cu-no': 'Cu-no', 'cyber_v': 'Cyber V',
    'cyborg_009': '再造人009', 'd-frag!': 'D-Frag!', 'daicon_iv': 'DAICON IV',
    'daiteikoku': '大帝国', 'delicious_party_precure': '美味派对光之美少女',
    'demi-chan_wa_kataritai': '亚人酱有话要说', 'dennou_shoujo_youtuber_siro': '电脑少女YouTuber白',
    'denonbu': '电音部', 'denpa_onna_to_seishun_otoko': '电波女与青春男',
    'devotion': '还愿', 'dewprism': '露水棱镜', 'di_gi_charat': 'Di Gi Charat',
    'dies_irae': 'Dies irae', 'dimension_w': 'Dimension W', 'dinosaur_king': '恐龙王者',
    'dirty_pair': '搞怪拍档', 'disney': '迪士尼', 'djmax': 'DJMAX',
    'dogs:_bullets_&_carnage': 'Dogs: Bullets & Carnage',
    'dohna_dohna_issho_ni_warui_koto_o_shiyou': '多娜多娜',
    'dokidoki!_precure': '心跳！光之美少女', 'doraemon': '哆啦A梦',
    'dorohedoro': '异兽魔都', 'dororon_enma-kun': '多罗罗炎魔君',
    'doukutsu_monogatari': '洞窟物语', 'doukyuusei': '同级生',
    'dracu-riot!': 'Dracu-Riot!', 'dragonaut': '龙鸣', 'drifters': '漂流者',
    'duel_masters': '决斗大师', 'eiken': 'Eiken', 'ekokuice': 'Ekokuice',
    'elemental_gelade': '武器种族传说', 'elysion': 'Elysion',
    'ero_condo': '工口公寓', 'eyeshield_21': '光速蒙面侠21',
    'fireball_series': '火球', 'firefox': 'Firefox', 'flcl': 'FLCL', 'flow': 'Flow',
    'fortune_arterial': 'Fortune Arterial', 'freezing_series': '零度战姬',
    'fresh_precure!': 'Fresh光之美少女！', 'fushigiboshi_no_futago_hime': '双子星公主',
    'futaba_channel': '双叶频道', 'ga-rei': '食灵', 'gad_guard': '钢铁守护者',
    'gaki_kyonyuu': '小鬼巨乳', 'gamers!': 'GAMERS!',
    'ganbare_douki-chan': '加油同期酱', 'ganbare_goemon': '加油五右卫门',
    'gatchaman': '科学小飞侠', 'garfield': '加菲猫',
    'getter_robo': '盖塔机器人', 'giant_robo': '大铁人',
    'gimai_seikatsu': '义妹生活', 'ginga_tetsudou_999': '银河铁道999',
    'girls_bravo': '女生万岁', 'go!_princess_precure': 'Go!Princess光之美少女',
    'good_omens': '好兆头', 'gorillaz': 'Gorillaz', 'grimgrimoire': '格林魔书',
    'grimms_notes': '格林笔记', 'gunsmith_cats': '铳梦CATS',
    'hajimete_no_gal': '第一次的辣妹', 'haks': 'HAKS',
    'hamidashi_creative': 'Hamidashi Creative', 'hapymaher': 'Hapymaher',
    'harry_potter_series': '哈利·波特', 'harukana_receive': '遥的接球',
    'heavy_object': '重装武器', 'hellboy_comic': '地狱男爵',
    'hello_charlotte': 'Hello Charlotte', 'heroman': 'HEROMAN',
    'hilda_series': '希尔达', 'himawari-san': '向日葵桑',
    'himitsu_no_aipri': '秘密的爱噗哩', 'hinako_note': '雏子笔记',
    'hitsugi_no_chaika': '棺姬嘉依卡', 'hokuto_no_ken': '北斗神拳',
    'honey_strap': 'Honey Strap', 'houkago_play': '放学后Play',
    'houkago_teibou_nisshi': '放学后海堤日记', 'hundred': 'Hundred',
    'i-chu': 'I★CHU', 'i_want_you': 'I Want You', 'ice_cream_kanojo': '冰淇淋女友',
    'id_:invaded': 'ID:INVADED', 'idol_land_pripara': '偶像乐园Pripara',
    'idoly_pride': 'IDOLY PRIDE', 'ikazuchi_no_senshi_raidy': '雷之战士莱蒂',
    'ikoku_meiro_no_croisee': '异国迷路的十字路口', 'imouto_sae_ireba_ii': '如果有妹妹就好了',
    'inabakumori': '稻叶曇', 'inari_konkon_koi_iroha.': '稻荷恋之歌',
    'indivisible': 'Indivisible', 'inhabituels': 'Inhabituels',
    'internet_explorer': 'Internet Explorer', 'invincible_series': '无敌少侠',
    'irisu_shoukougun!': 'Iris症候群！', 'isekai_maou_to_shoukan_shoujo_no_dorei_majutsu': '异世界魔王',
    'isekai_meikyuu_de_harem_wo': '异世界迷宫开后宫',
    'ishuzoku_reviewers': '异种族风俗娘评鉴指南',
    'itai_no_wa_iya_nano_de_bougyoryoku_ni_kyokufuri_shitai_to_omoimasu': '怕痛的我，把防御力点满就对了',
    'jibaku_shounen_hanako-kun': '地缚少年花子君', 'jigoku_sensei_nube': '地狱老师',
    'jingai_makyou': '刃鸣散', 'jinki': '人机', 'jinrui_wa_suitai_shimashita': '人类衰退之后',
    'kagaminomachi_no_kaguya': '镜之町的辉夜', 'kagurabachi': '神乐钵',
    'kaitou_saint_tail': '怪盗圣少女', 'kakyuusei': '下级生', 'kakyuusei_2': '下级生2',
    'kaleido_star': '卡莱多之星', 'kamen_america_comic': '假面美国漫画',
    'kami-sama_no_memo-chou': '神的记事本', 'kamichu!': '神是中学生！',
    'kamikaze_kaitou_jeanne': '神风怪盗贞德', 'kamisama_hajimemashita': '元气少女缘结神',
    'kamisama_ni_natta_hi': '成为神的那天', 'kampfer': '肯普法',
    'kannagi': '神薙', 'kanpani_girls': '看板娘少女',
    'karin_manga': '增血鬼果林', 'kashimashi': '女生爱女生',
    'katanagatari': '刀语', 'kekkai_sensen': '血界战线',
    'kemomimi_oukoku_kokuei_housou': '兽耳王国国营放送',
    'kemomimi_refle!': '兽耳Refle!', 'keroro_gunsou': 'Keroro军曹',
    'kfc': '肯德基', 'kick-ass': '海扁王',
    'kidou_keisatsu_patlabor': '机动警察Patlabor', 'kidou_senkan_nadesico': '机动战舰抚子号',
    'kim_possible_series': '麻辣女孩', 'kimi_ga_aruji_de_shitsuji_ga_ore_de': '你是主人我是仆',
    'kimi_ga_nozomu_eien': '你所期望的永远', 'kimi_kiss': '君吻',
    'kimi_no_koto_ga_dai_dai_dai_dai_daisuki_na_100-nin_no_kanojo': '超喜欢你的100个女朋友',
    'kin-iro_loveriche': '金色Loveriche', "knight's_&_magic": '骑士&魔法',
    'kizuna_ai_inc.': 'Kizuna AI', 'kmnz': 'KMNZ', 'kobe_shinbun': '神户新闻',
    'kodomo_no_jikan': '萝莉的时间', 'koe_no_katachi': '声之形',
    'koisuru_asteroid': '恋爱小行星', 'kokoro_connect': '心灵链环',
    'kono_bijutsubu_niwa_mondai_ga_aru!': '这个美术社大有问题！',
    'kono_yuusha_ga_ore_tueee_kuse_ni_shinchou_sugiru': '这个勇者明明超强却过分慎重',
    'kotoura-san': '琴浦小姐', 'koufuku_graffiti': '幸福涂鸦',
    'koukaku_no_pandora': '红壳的潘多拉', 'kujibiki_unbalance': '不平衡抽签',
    'kunio-kun_series': '热血系列', 'kusuriya_no_hitorigoto': '药屋少女的呢喃',
    'kyokou_suiri': '虚构推理', 'kyouran_kazoku_nikki': '狂乱家族日记',
    'kyousougiga': '京骚戏画', 'kyu-kurarin_cevio': 'Kyu-kurarin',
    "la_corda_d'oro": '金色琴弦', 'la_pucelle': '光之圣女',
    "ladies_versus_butlers!": '大小姐×管家！', "len'en": '连缘',
    'leon_the_professional': '这个杀手不太冷', 'lineage': '天堂',
    'little_red_riding_hood': '小红帽', 'little_witch_nobeta': '小魔女诺贝塔',
    'live_a_hero': 'Live A Hero', 'liver_city': 'Liver City',
    'lofi_girl_youtube': 'LoFi Girl', 'love_r': 'Love R',
    'lovely_x_cation_2': 'Lovely×Cation 2', 'lovers_game': '恋爱游戏',
    'luvdia': 'Luvdia', 'magical_halloween': '魔法万圣节',
    'magrona_channel': 'Magrona频道', 'mahoraba': '爱的魔法',
    'mahou_girls_precure!': '魔法使光之美少女！',
    'mahou_no_tenshi_creamy_mami': '魔法天使Creamy Mami',
    'mahou_shoujo_ai': '魔法少女爱', 'mahou_shoujo_pretty_sammy': '魔法少女Pretty Sammy',
    'mahou_shoujo_raita': '魔法少女Raita', 'mahou_tsukai_no_yoru': '魔法使之夜',
    'mahoujin_guruguru': '咕噜咕噜魔法阵', 'mahoutsukai_no_yakusoku': '魔法使的约定',
    'maid-san_wa_taberu_dake': '女仆只负责吃', 'maison_ikkoku': '相聚一刻',
    'majin_tantei_nougami_neuro': '魔人侦探食脑奈罗', 'majo_no_ie': '魔女之家',
    'majo_to_hyakkihei': '魔女与百骑兵', 'majutsushi_orphen': '魔术士欧菲',
    'makai_tenshi_djibril': '魔界天使Djibril', 'maoyuu_maou_yuusha': '魔王勇者',
    'maplestory': '冒险岛', 'marl_kingdom': '玛鲁王国',
    'mashiroiro_symphony': '纯白交响曲', 'mashle': '物理魔法使马修',
    'mazinger_series': '魔神系列', 'mechanical_buddy_universe': '机械伙伴宇宙',
    'medalist_manga': '奖牌获得者', 'meitantei_conan': '名侦探柯南',
    'melonbooks': 'Melonbooks', 'menhera-chan_ezaki_bisuko': '病娇酱',
    'meridian_project': 'Meridian Project', 'mewkledreamy': 'Mewkledreamy',
    'microsoft': '微软', 'mighty_no._9': '无敌9号', 'milgram': 'MILGRAM',
    'milk_inside_a_bag_of_milk_inside_a_bag_of_milk': '袋中袋牛奶',
    'miniskirt_pirates': '迷你裙海盗', 'miru_tights': '丝袜视界',
    'mitsudomoe': '超元气三姐妹', 'mm!': 'MM一族！',
    'mochipro': 'MochiPro', 'modao_zushi': '魔道祖师', 'mode_aim': 'Mode Aim',
    'mofu-mofu_after_school': '毛茸茸放学后', 'momotarou_densetsu': '桃太郎传说',
    'mon-musu_quest!': '魔物娘Quest!', 'monobeno': 'MonoBeno',
    'monster_high': '精灵高中', 'monster_manga': 'Monster', 'moomin': '姆明',
    'mother_game': '母娘乱馆', 'moyashimon': '萌菌物语', 'mugen_senshi_valis': '梦幻战士Valis',
    'muse_dash': 'Muse Dash', 'mushihime-sama': '虫姬さま', 'mushiking': '甲虫王者',
    'namco_x_capcom': '南梦宫×卡普空', 'namiuchigiwa_no_muromi-san': '人鱼又上钩',
    'nana_series': 'NANA', 'nanatsuiro_drops': '七色星露',
    'neo_ranga': '新·兰伽', 'night_wizard': 'Night Wizard',
    'nikki_series': '暖暖系列', 'ninin_ga_shinobuden': '2×2=忍传',
    'nippon_professional_baseball': '日本职棒', 'no.6': '未来都市No.6',
    'no_humans': '非人类', 'noble_witches': '贵族魔女', 'noein': '到另一个你的身边去',
    'nogizaka_haruka_no_himitsu': '乃木坂春香的秘密', 'nora_cat_channel': 'Nora Cat频道',
    'noripro': 'Noripro', 'nurse_witch_komugi-chan': '护士小魔女小麦',
    'oboro_muramasa': '胧村正', 'ochikobore_fruit_tart': '落第水果挞',
    'oda_nobuna_no_yabou': '织田信奈的野望', 'oku-sama_wa_joshi_kousei': '我太太是女子高中生',
    'omoide_no_marnie': '回忆中的玛妮', 'onegai_my_melody': '拜托了我的旋律',
    'onegai_teacher': '拜托了老师', 'onegai_twins': '拜托了双子星',
    'oneshot_game': 'OneShot', 'ongeki': '音击',
    'onna_shunin_kishi_mieko': '女主管骑士三重子', 'ookami-san': '大神与七位伙伴',
    'oshiete!_galko-chan': '告诉我！辣妹子酱', 'oshioki_sweetie': '惩罚甜心',
    'oshiro_project:re': '大城Project:Re', 'otogi-juushi_akazukin': '御伽草子 赤ずきん',
    'otome_domain': '少女领域', 'outlaw_star': '星方武侠',
    'paradox_live': 'Paradox Live', 'perfect_blue': '未麻的部屋',
    'pixiv': 'Pixiv', 'pixiv_fantasia': 'Pixiv Fantasia',
    "pop'n_music": "pop'n music", 'pop-up_story': 'Pop-up Story',
    'popful_mail': 'Popful Mail', 'predator_series': '铁血战士',
    'pretty_rhythm': '美妙旋律', 'production_kawaii': 'Production Kawaii',
    'promare': '普罗米亚', 'pumpkin_scissors': '南瓜剪刀',
    'puniru_wa_kawaii_slime': '噗尼露是可爱的史莱姆', 'pure_pure': 'Pure Pure',
    'qinshi_mingyue': '秦时明月', 'quiz_magic_academy': '问答魔法学院',
    'rabi-ribi': 'Rabi-Ribi', 'raging_loop': '人狼村之谜',
    'rail_wars!': 'RAIL WARS!', 're:act': 'Re:act',
    'read_or_die': '读或死', 'readymade_ado': 'Readymade Ado',
    'real_drive': 'RD潜脑调查室', 'real_life': '现实生活',
    'record_of_lodoss_war': '罗德岛战记', 'resort_boin': '度假村BOIN',
    'ribbon_no_kishi': '缎带骑士', 'riddle_joker': 'RIDDLE JOKER',
    'rinrinne': 'RinRinne', 'rumble_roses': '搏击玫瑰', 'rune_factory': '符文工厂',
    'ruri_dragon': '琉璃龙龙', 'ryuuko_no_ken': '龙虎之拳',
    'ryuuou_no_oshigoto!': '龙王的工作！', 'saenai_heroine_no_sodatekata': '路人女主的养成方法',
    'saibou_shinkyoku': '细胞神曲', 'sakamoto_days': '坂本日常',
    'sakura_musubi': '樱之杜†净梦者', 'samurai_champloo': '混沌武士',
    'san-x': 'San-X', 'sana_channel': 'Sana频道', 'sangokushi_taisen': '三国志大战',
    'sanoba_witch': '柚子社', 'saru_getchu': '捉猴啦',
    'sayonara_wo_oshiete': '说再见', 'scarz': 'SCARZ', 'scream_movie': '惊声尖叫',
    'seihou': '西方Project', 'seikai_no_senki': '星界之战旗',
    'seisenshi_dunbine': '圣战士丹拜因', 'seitokai_nimo_anawa_aru!': '学生会也有洞！',
    'seitokai_no_ichizon': '学生会的一存', 'seitokai_yakuindomo': '妄想学生会',
    'sekai_seifuku:_bouryaku_no_zvezda': '世界征服～谋略之星～',
    'sengoku_ace': '战国Ace', 'sengoku_basara': '战国BASARA',
    'sengoku_bushouki_muramasa': '战国武将姬Muramasa', 'sengoku_collection': '战国Collection',
    'sengoku_musou': '战国无双', 'senjou_no_valkyria_series': '战场女武神',
    'sennen_sensou_aigis': '千年战争Aigis', 'senren_banka': '千恋万花',
    'sergestid_shrimp_in_tungkang': '东港樱虾', 'seto_no_hanayome': '濑户的花嫁',
    'sexfriend': 'SexFriend', 'sf_choujigen_densetsu_rall': '幻界超次元传说Rall',
    'shadow_hearts': '影之心', 'shadows_house': '影宅', 'shelter_song': 'Shelter',
    "shijou_saikyou_no_deshi_ken'ichi": '史上最强弟子兼一',
    'shikkoku_no_sharnoth': '漆黑之Sharnoth', 'shimeji_simulation': '菌物模拟',
    'shimotsuma': '下妻', 'shin_kamen_rider': '新·假面骑士',
    'shin_sangoku_musou': '真·三国无双', 'shinigami_bocchan_to_kuro_maid': '死神少爷与黑女仆',
    'shining_nikki': '闪耀暖暖', 'shining_series': '光明系列', 'shinken-zemi': '进研ZEMI',
    'shinmai_fukei_kiruko-san': '新人警官 Kiruko',
    'shinmai_maou_no_testament': '新妹魔王的契约者', 'shino_to_ren': '诗乃与恋',
    'shinrabanshou': '神罗万象', 'shinryaku!_ikamusume': '侵略！乌贼娘',
    'shinsougumi': '新选组', 'shinza_bansho_series': '神座万象系列',
    'shirley_manga': '雪莉', 'shiroi_suna_no_aquatope': '白砂的水族馆',
    'shirokami_project': '白神Project', 'shironeko_project': '白猫Project',
    'shoujo_ramune': '少女波子汽水', 'shuumatsu_nani_shitemasu_ka?': '末日时在做什么？',
    'shuumatsu_no_izetta': '终末的伊泽塔', 'shy_series': 'SHY', 'signalis': 'SIGNALIS',
    "sisters_~natsu_no_saigo_no_hi~": 'SISTERS～夏日的最后一天～',
    'sky:_children_of_the_light': '光·遇', 'slay_the_princess': '杀公主',
    'slow_damage': 'Slow Damage', 'sola': 'sola', 'solo_leveling': '我独自升级',
    'solty_rei': 'Solty Rei', 'sora_no_iro_mizu_no_iro': '空之色水之色',
    'sora_wo_kakeru_shoujo': '穿越宇宙的少女', 'soredemo_machi_wa_mawatteiru': '女仆咖啡厅',
    'soukou_akki_muramasa': '装甲恶鬼村正', 'soukou_kihei_votoms': '装甲骑兵VOTOMS',
    'soul_hackers': '灵魂黑客', 'soulworker': '灵魂行者', 'sound_voltex': 'SOUND VOLTEX',
    'south_park': '南方公园', 'space_jam': '空中大灌篮',
    'space_maria': 'Space Maria', 'spy_kyoushitsu': '间谍教室',
    'star_driver': 'STAR DRIVER', 'strawberry_prince': '草莓王子',
    'streets_of_rage': '怒之铁拳', 'strider_video_game': '出击飞龙',
    'subarashiki_hibi': '美好的每一天', 'subarashiki_kono_sekai': '美妙的世界',
    'sugar_sugar_rune': '魔女的考验', 'suguri': 'Suguri',
    'suicide_boy': '自杀男孩', 'suigetsu': '水月',
    'sunoharasou_no_kanrinin-san': '春原庄的管理人', 'suntory': '三得利',
    'super_cub': '本田小狼与我', 'super_real_mahjong': '超级真实麻将',
    'surge_concerto': 'Surge Concerto', 'swapnote': '交换日记',
    'sword_girls': '剑之少女', 'tactics_ogre': '皇家骑士团',
    'taimanin_series': '对魔忍', 'talkex': 'TalkEx', 'tamatoys': 'Tamatoys',
    'tantei_wa_mou_shindeiru': '侦探已死', 'tayutama': '游魂',
    'teekyuu': '网球并不可笑嘛', 'tejina_senpai_series': '魔术学姐',
    'tekkaman_blade': '宇宙骑士利刃', 'tenchuu': '天诛', 'tengoku_daimakyou': '天国大魔境',
    'tenka_hyakken': '天华百剑', 'tensei_shitara_ken_deshita': '转生成为剑',
    'tenshi_no_3p!': '天使的3P！', 'tenshi_souzou_re-boot!': '天使创造Re-boot!',
    'tetsuwan_atom': '铁臂阿童木', 'the_adventures_of_sherlock_holmes': '福尔摩斯探案集',
    'the_crawling_city': '爬行都市', 'the_evil_within': '恶灵附身',
    'the_loud_house': '喧闹一家亲', 'the_moon_studio': 'The Moon Studio',
    'the_nightmare_before_christmas': '圣诞夜惊魂',
    'the_personification_of_atmosphere': '气氛拟人化', 'the_seven-year_itch': '七年之痒',
    'time_bokan_24': '时间飞船24', 'tiny_evil': 'Tiny Evil',
    'to_heart': 'To Heart', 'to_heart_series': 'To Heart系列',
    'toeto_虚拟歌手': 'Toeto虚拟歌手', 'toji_no_miko': '刀使巫女',
    'tokimeki_memorial': '心跳回忆', 'tomie': '富江',
    'tonari_no_kyuuketsuki-san': '邻家的吸血鬼小妹', 'tongkkangi': 'Tongkkangi',
    'top_wo_nerae!': '飞跃巅峰！', 'top_wo_nerae_2!': '飞跃巅峰2！',
    'toranoana': '虎之穴', 'toushinden': '斗神传', 'trickster': 'TRICKSTER',
    'trigger_heart_exelica': 'Trigger Heart Exelica', 'trinity_seven': 'TRINITY SEVEN',
    'true_tears': '真实之泪', 'trusty_bell': '信赖铃音',
    'tsukuyomi_moonphase': '月咏', 'tsunderia': 'Tsunderia',
    'twin_angel': '双胞胎天使', 'twinbee': '兵蜂', 'twitter-san': '推特桑',
    'uchuu_no_stellvia': '宇宙的星路', 'uchuu_senkan_yamato': '宇宙战舰大和号',
    'ueno-san_wa_bukiyou': '上野同学不器用', 'ukagaka': '伺か',
    'ultimate_nipper': '终极钳子', 'umihara_kawase': '海腹川背',
    'under_night_in-birth': '夜下降生', 'uni_create': 'UNI CREATE',
    'urara_meirochou': '乌菈菈迷路帖', 'urusei_yatsura': '福星小子',
    'usseewa': 'Usseewa', 'utakata': '诗片', 'utau': 'UTAU',
    'vampire_game': '恶魔战士', 'vampirella': 'Vampirella',
    'vanguard_princess': 'Vanguard Princess', 'veil_manga': 'Veil',
    'versailles_no_bara': '凡尔赛玫瑰', 'victorian_romance_emma': '英国恋爱物语艾玛',
    'vinesauce': 'Vinesauce', 'viper': 'VIPER', 'viper_rsr': 'VIPER RSR',
    'virtual_on': '电脑战机', 'voisona': 'VoiSona',
    'voltron:_legendary_defender': '战神金刚：传奇护卫', 'voms': 'VOMS',
    'vrchat': 'VRChat', 'vyugen': 'Vyugen', 'wactor_production': 'WACTOR',
    'wagaya_no_oinari-sama': '我家的狐仙大人', 'waktaverse': 'WaktaVerse',
    'waku_waku_7': '火热火热7', 'walkure_romanze': '少女骑士物语',
    'wanmei_shijie': '完美世界', 'wario_land': '瓦力欧大陆', 'warioware': '瓦力欧制造',
    'watchmen': '守望者', "wendy's": "Wendy's", 'white_album_series': '白色相簿',
    'wii_fit': 'Wii Fit', 'wikipedia': '维基百科',
    'wind_breaker_nii_satoru': '防风铃', 'witchblade': '魔女之刃',
    'with_you': 'With You', 'wixoss': 'WIXOSS', 'wonder_egg_priority': '奇蛋物语',
    'wonder_momo': 'Wonder Momo', 'words_worth': 'Words Worth',
    'wrestle_angels': '摔角天使', 'xianjian_qixia_zhuan': '仙剑奇侠传', 'xxxholic': 'XXXHOLiC',
    'yakitate!!_japan': '日式面包王', 'yami_to_boushi_to_hon_no_tabibito': '暗与帽子与书的旅人',
    'yatterman': '小双侠', 'yesterday_wo_utatte': '昨日之歌',
    'yoake_mae_yori_ruri_iro_na': '夜明前的琉璃色', 'yojouhan_shinwa_taikei': '四叠半神话大系',
    'yokohama_kaidashi_kikou': '横滨购物纪行', 'yoru_no_kurage_wa_oyogenai': '夜晚的水母不会游泳',
    'yoru_no_yatterman': '夜之小双侠', 'yotsunoha': '四叶草',
    'your_diary': 'Your Diary', 'yuni_channel': 'Yuni频道',
    'yuusha_de_aru': '勇者である', 'yuusha_series': '勇者系列', 'yuusha_to_maou': '勇者与魔王',
    'zegapain': 'ZEGAPAIN', 'zero_kara_hajimeru_mahou_no_sho': '从零开始的魔法书',
    'zettai_karen_children': '绝对可怜Children', 'natsume_yuujinchou': '夏目友人帐',
    '高達': '高达', '高达系列': '高达',
    'dororo': '多罗罗', 'fate_apocrypha': 'Fate/Apocrypha', 'fate_zero': 'Fate/Zero',
    'fate_extra': 'Fate/EXTRA', 'fate_prototype': 'Fate/Prototype',
    'fate_strange_fake': 'Fate/strange Fake', 'fate_samurai_remnant': 'Fate/Samurai Remnant',
    'girls_frontline_2': '少女前线2', 'exilium': '少女前线2',
    'punishing_gray_raven_global': '战双帕弥什', 'wuthering_waves_global': '鸣潮',
    'honkai_star_rail_global': '崩坏：星穹铁道', 'honkai_impact_3rd': '崩坏3',
    'genshin_impact_global': '原神', 'zzz': '绝区零',
    'reverse_1999_global': '重返未来1999', 'path_to_nowhere': '无期迷途',
    'neural_cloud': '云图计划', 'girls_frontline_neural': '云图计划',
    'arknights_endfield': '明日方舟：终末地', 'endfield': '明日方舟终末地',
    'azur_lane_crosswave': '碧蓝航线 Crosswave', 'azur_lane_anime': '碧蓝航线 动画',
    'kancolle_anime': '舰队Collection 动画', '艦これ': '舰队Collection',
    'touhou_project': '东方Project', 'touhou': '东方Project',
    'azure_lane': '碧蓝航线', 'azurlane': '碧蓝航线',
    'girls_frontline_anime': '少女前线 动画', 'gfl': '少女前线',
    'blue_archive_global': '碧蓝档案', 'arknights_anime': '明日方舟 动画',
    'AK': '明日方舟', 'BA': '碧蓝档案', 'GI': '原神', 'HSR': '崩坏：星穹铁道',
    'ZZZ': '绝区零', 'PGR': '战双帕弥什', 'AL': '碧蓝航线', 'KC': '舰队Collection',
    'GF': '少女前线', 'AKA': '碧蓝档案', 'HI3': '崩坏3',
    'hololive_en': 'Hololive EN', 'hololive_id': 'Hololive ID',
    'hololive_myth': 'Hololive Myth', 'hololive_council': 'Hololive Council',
    'hololive_advent': 'Hololive Advent', 'hololive_justice': 'Hololive Justice',
    'hololive_gamers': 'Hololive Gamers', 'hololive_fantasy': 'Hololive Fantasy',
    'holostars': 'Holostars', 'holostars_en': 'Holostars EN',
    'nijisanji': '彩虹社', 'nijisanji_en': '彩虹社EN', 'nijisanji_id': '彩虹社ID',
    'nijisanji_kr': '彩虹社KR', 'vspo_en': 'VSPO! EN',
    'vshojo_jp': 'VShojo JP', 'phase_connect_jp': 'Phase Connect JP',
    'idol_corp': 'idol Corp', 'idol_en': 'idol EN',
    'neo-porte': 'Neo-Porte', 'specialite': 'Specialite',
    'first_stage_production': 'First Stage Production', '774inc': '774 inc.',
    're:act_en': 'Re:ACT EN', 'dot_live': '.LIVE',
    'game_bu_project': '游戏部Project', 'lupinus_virtual_games': 'Lupinus Virtual Games',
    'marvellous': 'Marvellous', 'animare_vtuber': 'Animare', 'honeystrap': 'HoneyStrap',
    'upd8': 'upd8', 'ichikara': 'ANYCOLOR', 'cover_corp': 'COVER Corp.',
    'brave_group': 'Brave Group', 'vtuber': '虚拟主播',
    'cevio_ai': 'CeVIO AI', 'synthesizer_v_studio': 'Synthesizer V Studio',
    'voicevox_engine': 'VOICEVOX', 'voiceroid_2': 'VOICEROID2',
    'neutrino': 'NEUTRINO', 'coeiroink': 'COEIROINK',
    'aivoice': 'A.I.VOICE', 'cevio_cs': 'CeVIO CS', 'vocaloid6': 'VOCALOID6',
    'piapro': 'Piapro', 'crypton': 'Crypton', 'utau_software': 'UTAU',
    'vocaloid_3': 'VOCALOID3', 'vocaloid_4': 'VOCALOID4', 'vocaloid_5': 'VOCALOID5',
    'openutau': 'OpenUTAU', 'diff_singer': 'DiffSinger', 'ace_studio': 'ACE Studio',
    'x_studio': 'X Studio', 'ntred': 'NTRed', 'alter_ego': 'Alter/Ego',
    'synthesizer_v_ai': 'Synthesizer V AI',
    'eureka_seven': '交响诗篇', 'kill_la_kill_game': '斩服少女 游戏',
    'gundam': '高达', '機動戦士ガンダム': '高达',
    '高达系列': '高达', 'Gundam': '高达', 'gundam_series': '高达',
    'macross': '超时空要塞', 'macross_delta': '超时空要塞Δ',
    'macross_frontier': '超时空要塞F', 'macross_7': '超时空要塞7',
    'macross_plus': '超时空要塞PLUS', 'macross_zero': '超时空要塞ZERO',
    'robotech': '太空堡垒', 'votoms': '装甲骑兵', 'dougram': '太阳之牙',
    'layzner': '苍之流星', 'dragonar': '机甲猎兵', 'galient': '机甲界',
    'patlabor': '机动警察', 'giant_robo_oav': '大铁人 OVA', 'gaogaigar': '勇者王',
    'gurren_lagann': '天元突破', 'evangelion': '新世纪福音战士', 'eva': '新世纪福音战士',
    '超时空要塞': '超时空要塞', 'Gundam_series': '高达',
    'initial_d': '头文字D', 'wangan_midnight': '湾岸午夜',
    'over_rev': 'Over Rev!', 'mf_ghost_manga': 'MF GHOST',
    'capeta': '极速方程式', 'speed_racer': '极速赛车手',
    'redline': '红线', 'tailenders': 'Tailenders',
    'kamen_rider_series': '假面骑士', 'super_sentai': '超级战队',
    'ultraman': '奥特曼', 'ultraman_series': '奥特曼系列',
    'power_rangers': '恐龙战队', 'garo': '牙狼', 'amazon_rider': '假面骑士Amazons',
    'black_sun': '假面骑士Black Sun', 'shin_ultraman': '新·奥特曼',
    'shin_kamen_rider_2023': '新·假面骑士', 'fuuto_pi': '风都侦探',
    'precure': '光之美少女', 'precure_series': '光之美少女系列',
    'futari_wa_precure': '光之美少女', 'max_heart': '光之美少女 Max Heart',
    'splash_star': '光之美少女Splash Star', 'yes_precure_5': 'Yes!光之美少女5',
    'fresh_precure': 'Fresh光之美少女！', 'heartcatch_precure': 'HeartCatch光之美少女！',
    'suite_precure': 'Suite光之美少女♪', 'smile_precure': 'Smile光之美少女！',
    'dokidoki_precure': '心跳！光之美少女', 'happinesscharge_precure': 'HappinessCharge光之美少女！',
    'go_princess_precure': 'Go!Princess光之美少女', 'mahoutsukai_precure': '魔法使光之美少女！',
    'kirakira_precure': 'KiraKira☆光之美少女', 'hugtto_precure': 'HUGtto!光之美少女',
    'star_twinkle_precure': '星光☆闪亮光之美少女', 'healingood_precure': 'Healin\' Good ♡ 光之美少女',
    'tropical_rouge_precure': 'Tropical-Rouge!光之美少女',
    'delicious_party_precure_anime': '美味派对♡光之美少女',
    'hirogaru_sky_precure': '广阔天空！光之美少女',
    'wonderful_precure': 'Wonderful光之美少女！',
    'happinesscharge_precure!': 'HappinessCharge光之美少女！',
    'heartcatch_precure!': 'HeartCatch光之美少女！',
    'healin\'_good_precure': 'Healin\' Good ♡ 光之美少女',
    'hirogaru_sky!_precure': '广阔天空！光之美少女',
    'kirakira_precure_a_la_mode': 'KiraKira光之美少女',
    'mahou_girls_precure!': '魔法使光之美少女！',
    'dokidoki!_precure': '心跳！光之美少女',
    'fresh_precure!': 'Fresh光之美少女！',
    'snow_white': '白雪公主', 'snow_white_and_the_seven_dwarfs': '白雪公主与七个小矮人',
    'kh3': '王国之心III', 'kh2': '王国之心II', 'kingdom_hearts_3': '王国之心III',
    'kingdom_hearts_2': '王国之心II', 'kingdom_hearts_358': '王国之心 358/2天',
    'kingdom_hearts_bbs': '王国之心 梦中降生', 'kingdom_hearts_ddd': '王国之心 3D',
    'kingdom_hearts_ux': '王国之心 Union χ', 'kingdom_hearts_dark_road': '王国之心 黑暗之路',
    'kingdom_hearts_ml': '王国之心 Missing-Link', 'kingdom_hearts_4': '王国之心IV',
    'melody_of_memory': '王国之心 记忆旋律',
    'final_fantasy_vii': '最终幻想VII', 'ff7': '最终幻想VII',
    'final_fantasy_x': '最终幻想X', 'ffx': '最终幻想X',
    'final_fantasy_xiv': '最终幻想XIV', 'ff14': '最终幻想XIV',
    'final_fantasy_xv': '最终幻想XV', 'ff15': '最终幻想XV',
    'final_fantasy_xvi': '最终幻想XVI', 'ff16': '最终幻想XVI',
    'final_fantasy_ix': '最终幻想IX', 'ff9': '最终幻想IX',
    'final_fantasy_viii': '最终幻想VIII', 'ff8': '最终幻想VIII',
    'final_fantasy_vi': '最终幻想VI', 'ff6': '最终幻想VI',
    'final_fantasy_v': '最终幻想V', 'ff5': '最终幻想V',
    'final_fantasy_iv': '最终幻想IV', 'ff4': '最终幻想IV',
    'final_fantasy_xiii': '最终幻想XIII', 'ff13': '最终幻想XIII',
    'final_fantasy_xii': '最终幻想XII', 'ff12': '最终幻想XII',
    'final_fantasy_tactics': '最终幻想战略版', 'fft': '最终幻想战略版',
    'final_fantasy_type_0': '最终幻想 零式', 'type0': '最终幻想 零式',
    'final_fantasy_crystal_chronicles': '最终幻想水晶编年史', 'ffcc': '最终幻想水晶编年史',
    'world_of_final_fantasy': '最终幻想世界', 'woff': '最终幻想世界',
    'dissidia_final_fantasy': '最终幻想 纷争', 'dissidia': '最终幻想 纷争',
    'stranger_of_paradise': '最终幻想 起源', 'sopffo': '最终幻想 起源',
    'ff7_remake': '最终幻想VII 重制版', 'ff7_rebirth': '最终幻想VII 重生',
    'ff7_ever_crisis': '最终幻想VII Ever Crisis', 'ff7_first_soldier': '最终幻想VII The First Soldier',
    'ffxiv_a_realm_reborn': '最终幻想XIV 重生之境', 'ffxiv_heavensward': '最终幻想XIV 苍穹之禁城',
    'ffxiv_stormblood': '最终幻想XIV 红莲之狂潮', 'ffxiv_shadowbringers': '最终幻想XIV 暗影之逆焰',
    'ffxiv_endwalker': '最终幻想XIV 晓月之终途', 'ffxiv_dawntrail': '最终幻想XIV 黄金的遗产',
    'nier_automata_anime': '尼尔：自动人形', 'nier_replicant': '尼尔 人工生命',
    'nier_reincarnation': '尼尔 Re[in]carnation', 'drakengard': '龙背上的骑兵',
    'dragon_quest_xi': '勇者斗恶龙XI', 'dq11': '勇者斗恶龙XI',
    'dragon_quest_viii': '勇者斗恶龙VIII', 'dq8': '勇者斗恶龙VIII',
    'dragon_quest_v': '勇者斗恶龙V', 'dq5': '勇者斗恶龙V',
    'dragon_quest_iv': '勇者斗恶龙IV', 'dq4': '勇者斗恶龙IV',
    'dragon_quest_iii': '勇者斗恶龙III', 'dq3': '勇者斗恶龙III',
    'dragon_quest_builders': '勇者斗恶龙 创世小玩家', 'dqb': '勇者斗恶龙 创世小玩家',
    'dragon_quest_monsters': '勇者斗恶龙 怪兽篇', 'dqm': '勇者斗恶龙 怪兽篇',
    'dragon_quest_heroes': '勇者斗恶龙 英雄', 'dqh': '勇者斗恶龙 英雄',
    'dragon_quest_treasures': '勇者斗恶龙 寻宝探险团', 'dqt': '勇者斗恶龙 寻宝探险团',
    'infinity_strash': '勇者斗恶龙 达伊的大冒险', 'dai': '达伊的大冒险',
    'pokemon_red_blue': '宝可梦 红/绿', 'pokemon_gold_silver': '宝可梦 金/银',
    'pokemon_ruby_sapphire': '宝可梦 红宝石/蓝宝石', 'pokemon_diamond_pearl': '宝可梦 钻石/珍珠',
    'pokemon_black_white': '宝可梦 黑/白', 'pokemon_x_y': '宝可梦 X/Y',
    'pokemon_sun_moon': '宝可梦 太阳/月亮', 'pokemon_sword_shield': '宝可梦 剑/盾',
    'pokemon_scarlet_violet': '宝可梦 朱/紫', 'pokemon_legends_arceus': '宝可梦传说 阿尔宙斯',
    'pokemon_legends_z_a': '宝可梦传说 Z-A', 'pokemon_lets_go': '宝可梦 Let\'s Go!',
    'pokemon_brilliant_diamond_shining_pearl': '宝可梦 晶灿钻石/明亮珍珠',
    'pokemon_omega_ruby_alpha_sapphire': '宝可梦 欧米伽红宝石/阿尔法蓝宝石',
    'pokemon_ultra_sun_ultra_moon': '宝可梦 究极之日/究极之月',
    'pokemon_mystery_dungeon': '宝可梦不可思议迷宫', 'pokemon_ranger': '宝可梦巡护员',
    'pokemon_conquest': '宝可梦+信长的野望', 'pokken_tournament': '宝可拳',
    'pokemon_unite': '宝可梦大集结', 'pokemon_masters': '宝可梦大师',
    'pokemon_cafe': '宝可梦Cafe Mix', 'pokemon_sleep': '宝可梦Sleep',
    'pokemon_go': '宝可梦GO', 'pokemon_tcg': '宝可梦卡牌',
    'fire_emblem_shadow_dragon': '火焰纹章 暗黑龙与光之剑',
    'fire_emblem_gaiden': '火焰纹章 外传', 'fire_emblem_mystery': '火焰纹章 纹章之谜',
    'fire_emblem_genealogy': '火焰纹章 圣战之系谱', 'fire_emblem_thracia': '火焰纹章 多拉基亚776',
    'fire_emblem_binding_blade': '火焰纹章 封印之剑', 'fire_emblem_blazing_blade': '火焰纹章 烈火之剑',
    'fire_emblem_sacred_stones': '火焰纹章 圣魔之光石', 'fire_emblem_path_of_radiance': '火焰纹章 苍炎之轨迹',
    'fire_emblem_radiant_dawn': '火焰纹章 晓之女神', 'fire_emblem_awakening': '火焰纹章 觉醒',
    'fire_emblem_fates': '火焰纹章 if', 'fire_emblem_echoes': '火焰纹章 Echoes',
    'fire_emblem_three_houses': '火焰纹章 风花雪月', 'fire_emblem_engage': '火焰纹章 Engage',
    'fire_emblem_heroes': '火焰纹章 英雄', 'fire_emblem_warriors': '火焰纹章无双',
    'fe_shadow_dragon': '火焰纹章 暗黑龙', 'fe_new_mystery': '火焰纹章 新·纹章之谜',
    'tokyo_mirage_sessions': '幻影异闻录♯FE', 'fe_warriors_three_hopes': '火焰纹章无双 风花雪月',
    'atelier_ryza': '莱莎的炼金工房', 'atelier_ryza_2': '莱莎的炼金工房2',
    'atelier_ryza_3': '莱莎的炼金工房3', 'atelier_sophie': '苏菲的炼金工房',
    'atelier_firis': '菲莉丝的炼金工房', 'atelier_lydie_suelle': '莉迪&苏瑞的炼金工房',
    'atelier_lulua': '露露亚的炼金工房', 'atelier_esca_logy': '爱丝卡&罗吉的炼金工房',
    'atelier_ayesha': '爱夏的炼金工房', 'atelier_shallie': '夏莉的炼金工房',
    'atelier_totori': '托托莉的炼金工房', 'atelier_meruru': '梅露露的炼金工房',
    'atelier_rorona': '罗罗娜的炼金工房', 'atelier_marie': '玛莉的炼金工房',
    'atelier_elie': '艾莉的炼金工房', 'atelier_lilie': '莉莉的炼金工房',
    'atelier_judie': '尤蒂的炼金工房', 'atelier_viorate': '薇欧蕾特的炼金工房',
    'atelier_iris': '伊莉丝的炼金工房', 'atelier_mana_khemia': '玛娜传奇',
    'atelier_resleriana': '莱斯蕾莉安娜的炼金工房', 'atelier_online': '炼金工房Online',
    'nelke': '奈尔克与传说的炼金术士们', 'arland': '亚兰德炼金术士',
    'dusk': '黄昏炼金术士', 'mysterious': '不可思议炼金术士',
    'secret': '秘密炼金术士', 'atelier': '炼金工房',
    'tales_of_phantasia': '幻想传说', 'tales_of_destiny': '宿命传说',
    'tales_of_eternia': '永恒传说', 'tales_of_destiny_2': '宿命传说2',
    'tales_of_symphonia': '仙乐传说', 'tales_of_rebirth': '重生传说',
    'tales_of_legendia': '神话传说', 'tales_of_the_abyss': '深渊传说',
    'tales_of_innocence': '纯真传说', 'tales_of_vesperia': '宵星传说',
    'tales_of_hearts': '心灵传说', 'tales_of_graces': '圣恩传说',
    'tales_of_xillia': '无尽传说', 'tales_of_xillia_2': '无尽传说2',
    'tales_of_zestiria': '热情传说', 'tales_of_berseria': '绯夜传奇',
    'tales_of_arise': '破晓传说', 'tales_of_luminaria': 'Tales of Luminaria',
    'tales_of_crestoria': 'Tales of Crestoria', 'tales_of_the_rays': 'Tales of the Rays',
    'tales_of_link': 'Tales of Link', 'tales_of_asteria': 'Tales of Asteria',
    'persona_3': '女神异闻录3', 'persona_4': '女神异闻录4', 'persona_5': '女神异闻录5',
    'p3': '女神异闻录3', 'p4': '女神异闻录4', 'p5': '女神异闻录5',
    'persona_1': '女神异闻录', 'persona_2': '女神异闻录2',
    'p2is': '女神异闻录2 罪', 'p2ep': '女神异闻录2 罚',
    'persona_3_portable': '女神异闻录3 携带版', 'persona_3_fes': '女神异闻录3 FES',
    'persona_3_reload': '女神异闻录3 Reload', 'persona_4_golden': '女神异闻录4 黄金版',
    'persona_5_royal': '女神异闻录5 皇家版', 'persona_5_strikers': '女神异闻录5 乱战：魅影攻手',
    'persona_5_tactica': '女神异闻录5 战略版', 'persona_5_dancing': '女神异闻录5 星夜热舞',
    'persona_4_dancing': '女神异闻录4 通宵热舞', 'persona_3_dancing': '女神异闻录3 月夜热舞',
    'persona_q': '女神异闻录Q', 'persona_q2': '女神异闻录Q2',
    'shin_megami_tensei_i': '真女神转生', 'smt1': '真女神转生',
    'shin_megami_tensei_ii': '真女神转生II', 'smt2': '真女神转生II',
    'shin_megami_tensei_iii': '真女神转生III-NOCTURNE', 'smt3': '真女神转生III',
    'smt_nocturne': '真女神转生III', 'shin_megami_tensei_iv': '真女神转生IV',
    'smt4': '真女神转生IV', 'shin_megami_tensei_iv_final': '真女神转生IV FINAL',
    'smt_iv_apocalypse': '真女神转生IV FINAL', 'shin_megami_tensei_v': '真女神转生V',
    'smt5': '真女神转生V', 'smt_v_vengeance': '真女神转生V Vengeance',
    'devil_summoner': '恶魔召唤师', 'soul_hackers_series': '灵魂黑客',
    'soul_hackers_2': '灵魂黑客2', 'devil_survivor_1': '恶魔幸存者',
    'devil_survivor_2': '恶魔幸存者2', 'devil_children': '恶魔之子',
    'digital_devil_saga': '数码恶魔传说', 'dds': '数码恶魔传说',
    'raidou_kuzunoha': '葛叶雷道', 'raidou': '葛叶雷道',
    'last_bible': 'Last Bible', 'majin_tensei': '魔神转生',
    'devil_summoner_raidou': '恶魔召唤师 葛叶雷道',
    'tokyo_mirage_sessions_fe': '幻影异闻录♯FE',
    'jack_bros': 'Jack Bros.', 'smt_if': '真·女神转生if...',
    'smt_nine': '真·女神转生NINE', 'smt_imagine': '真·女神转生IMAGINE',
    'smt_strange_journey': '真·女神转生 STRANGE JOURNEY',
    'smt_synchonicity': '真·女神转生 SYNCHRONICITY PROLOGUE',
    'persona_trinity_soul': '女神异闻录 ~Trinity Soul~',
    'the_legend_of_zelda': '塞尔达传说', 'zelda': '塞尔达传说',
    'ocarina_of_time': '塞尔达传说 时之笛', 'majora_mask': '塞尔达传说 姆吉拉的假面',
    'wind_waker': '塞尔达传说 风之杖', 'twilight_princess': '塞尔达传说 黄昏公主',
    'skyward_sword': '塞尔达传说 天空之剑', 'breath_of_the_wild': '塞尔达传说 旷野之息',
    'tears_of_the_kingdom': '塞尔达传说 王国之泪', 'link_awakening': '塞尔达传说 织梦岛',
    'a_link_to_the_past': '塞尔达传说 众神的三角力量', 'link_between_worlds': '塞尔达传说 众神的三角力量2',
    'phantom_hourglass': '塞尔达传说 幻影沙漏', 'spirit_tracks': '塞尔达传说 大地的汽笛',
    'minish_cap': '塞尔达传说 缩小帽', 'oracle_of_ages': '塞尔达传说 时空之章',
    'oracle_of_seasons': '塞尔达传说 大地之章', 'four_swords': '塞尔达传说 四支剑',
    'tri_force_heroes': '塞尔达传说 三角力量英雄', 'hyrule_warriors_definitive': '塞尔达传说无双 海拉鲁全明星',
    'cadence_of_hyrule': '凯登丝勇闯海拉鲁', 'zelda_no_densetsu': '塞尔达传说',
    'xenoblade_1': '异度之刃', 'xenoblade_2': '异度之刃2', 'xenoblade_3': '异度之刃3',
    'xb1': '异度之刃', 'xb2': '异度之刃2', 'xb3': '异度之刃3',
    'xenoblade_definitive': '异度之刃 终极版', 'xenoblade_x': '异度之刃X',
    'torna': '异度之刃2 黄金之国伊拉', 'future_connected': '异度之刃 相连的未来',
    'future_redeemed': '异度之刃3 崭新的未来', 'xenosaga_i': '异度传说 一章',
    'xenosaga_ii': '异度传说 二章', 'xenosaga_iii': '异度传说 三章',
    'xenogears_game': '异度装甲', 'xenoblade_series': '异度之刃系列',
    'xeno': '异度系列', 'monolith_soft': 'Monolith Soft',
    'guilty_gear_xx': '罪恶装备XX', 'guilty_gear_xrd': '罪恶装备Xrd',
    'guilty_gear_strive': '罪恶装备 -Strive-', 'blazblue_calamity_trigger': '苍翼默示录',
    'blazblue_continuum_shift': '苍翼默示录 CS', 'blazblue_chrono_phantasma': '苍翼默示录 CP',
    'blazblue_central_fiction': '苍翼默示录 CF', 'blazblue_alternative': '苍翼默示录 交叉组队战',
    'blazblue_entropy_effect': '苍翼：混沌效应', 'blazblue_dark_war': '苍翼默示录 黑暗大战',
    'arc_system_works': 'Arc System Works', 'ggst': '罪恶装备 -Strive-',
    'blazblue_cf': '苍翼默示录 CF', 'dragon_ball_fighterz': '龙珠斗士Z',
    'granblue_fantasy_versus': '碧蓝幻想Versus', 'gbvs': '碧蓝幻想Versus',
    'granblue_fantasy_relink': '碧蓝幻想Relink', 'gbvsr': '碧蓝幻想Versus -Rising-',
    'dnf_duel': 'DNF Duel', 'uni': '夜下降生',
    'under_night_in_birth': '夜下降生', 'uni2': '夜下降生II',
    'melty_blood': 'Melty Blood', 'melty_blood_type_lumina': 'Melty Blood: Type Lumina',
    'fate_unlimited_codes': 'Fate/unlimited codes', 'fate_extella': 'Fate/EXTELLA',
    'fate_extella_link': 'Fate/EXTELLA LINK', 'fate_samurai_remnant_game': 'Fate/Samurai Remnant',
    'tsukihime_remake': '月姬 -A piece of blue glass moon-',
    'mahoutsukai_no_yoru_vn': '魔法使之夜', 'witch_on_the_holy_night': '魔法使之夜',
    'mahoyo': '魔法使之夜', 'kara_no_kyoukai_movies': '空之境界',
    'garden_of_sinners': '空之境界', 'fate_stay_night': 'Fate/stay night',
    'fate_hollow_ataraxia': 'Fate/hollow ataraxia', 'fate_grand_order_arcade': 'Fate/Grand Order Arcade',
    'fate_type_redline': 'Fate/type Redline', 'fate_lost_einherjar': 'Fate:Lost Einherjar',
    'fate_requiem': 'Fate/Requiem', 'fate_strange_fake_anime': 'Fate/strange Fake',
    'fate_kaleid_liner_prisma_illya': 'Fate/kaleid liner 魔法少女☆伊莉雅',
    'prisma_illya': '魔法少女☆伊莉雅', 'fate_cooking': '卫宫家今天的饭',
    'emiya_gohan': '卫宫家的饭', 'today_menu_emiya_family': '卫宫家今天的饭',
    'carnival_phantasm': '幻想嘉年华', 'fate_grand_carnival': 'Fate/Grand Carnival',
    'all_around_type_moon': 'TAKE MOON', 'bamboo_broom': '竹帚',
    'type_moon': 'TYPE-MOON', 'typemoon': 'TYPE-MOON', 'notes': 'Notes.',
    'angel_notes': 'Angel Notes', 'dd': '月之珊瑚', 'tsuki_no_sango': '月之珊瑚',
    'tsukihime_original': '月姬', 'shingetsutan_tsukihime': '真月谭月姬',
    'Kagetsu_Tohya': '歌月十夜', 'melty_blood_original': 'Melty Blood',
    'fgo': 'Fate/Grand Order', 'fg_o': 'Fate/Grand Order',
    'love_live_school_idol_festival': 'LoveLive!学园偶像祭', 'sif': '学园偶像祭',
    'love_live_sif_all_stars': 'LoveLive!学园偶像祭ALL STARS', 'sifas': '学园偶像祭ALL STARS',
    'love_live_superstar_anime': 'LoveLive!Superstar!!', 'love_live_nijigasaki_anime': 'LoveLive!虹咲学园',
    'love_live_sunshine_anime': 'LoveLive!Sunshine!!', 'love_live_movie': 'LoveLive!学园偶像电影',
    'aquors': 'Aqours', 'muse': 'μ\'s', 'liella': 'Liella!',
    'nijigasaki': '虹咲学园学园偶像同好会', 'a_r_i_s_e': 'A-RISE',
    'saint_snow': 'Saint Snow', 'sunny_passion': 'Sunny Passion',
    'yuigaoka': '结丘女子高等学校', 'otonokizaka': '音乃木坂学院',
    'uranohoshi': '浦之星女学院', 'y_g_international': 'Y.G.国际学园',
    'hasunosora': '莲之空女学院', 'kasukabe': '春日部',
    'bang_dream_anime': 'BanG Dream!', 'bang_dream_season2': 'BanG Dream! 2nd Season',
    'bang_dream_season3': 'BanG Dream! 3rd Season', 'bang_dream_film_live': 'BanG Dream! FILM LIVE',
    'bang_dream_mygo': 'BanG Dream! It\'s MyGO!!!!!', 'bang_dream_ave_mujica': 'BanG Dream! Ave Mujica',
    'poppin_party': 'Poppin\'Party', 'afterglow': 'Afterglow',
    'pastel_palettes': 'Pastel*Palettes', 'roselia': 'Roselia',
    'hello_happy_world': 'Hello, Happy World!', 'morfonica': 'Morfonica',
    'raise_a_suilen': 'RAISE A SUILEN', 'mygo': 'MyGO!!!!!',
    'ave_mujica': 'Ave Mujica', 'garupa': 'BanG Dream! 少女乐团派对',
    'd4dj_first_mix': 'D4DJ First Mix', 'd4dj_all_mix': 'D4DJ All Mix',
    'happy_around': 'Happy Around!', 'peaky_p-key': 'Peaky P-key',
    'photon_maiden': 'Photon Maiden', 'merm4id': 'Merm4id',
    'rondo': 'RONDO', 'lyrical_lily': 'Lyrical Lily',
    'call_of_artemis': 'Call of Artemis', 'unichord': 'UniChØrd',
    'abyssmare': 'Abyssmare', 'd4dj_groovy_mix': 'D4DJ Groovy Mix',
    'project_sekai_colorful_stage': '世界计划 彩色舞台', 'proseka': '世界计划',
    'puroseka': '世界计划', 'hatsune_miku_colorful_stage': '世界计划',
    'leo_need': 'Leo/need', 'more_more_jump': 'MORE MORE JUMP!',
    'vivid_bad_squad': 'Vivid BAD SQUAD', 'wonderlands_x_showtime': 'Wonderlands×Showtime',
    'nightcord_at_25': '25时、Nightcordで。', 'niigo': '25时',
    'leo_need_vocaloid': 'Leo/need', 'mmj': 'MORE MORE JUMP!',
    'vbs': 'Vivid BAD SQUAD', 'wxs': 'Wonderlands×Showtime',
    'niigo_virtual_singer': '25时',
    'idolmaster_cinderella_girls': '偶像大师 灰姑娘女孩', 'deresute': '偶像大师 灰姑娘女孩',
    'idolmaster_million_live': '偶像大师 MILLION LIVE!', 'mirishita': '偶像大师 MILLION LIVE!',
    'idolmaster_shiny_colors': '偶像大师 SHINY COLORS', 'shanimas': '偶像大师 SHINY COLORS',
    'idolmaster_side_m': '偶像大师 SideM', 'idolmaster_xenoglossia': '偶像大师 XENOGLOSSIA',
    '765pro': '765 Production', '346pro': '346 Production', '315pro': '315 Production',
    '283pro': '283 Production', '961pro': '961 Production',
    'cinderella_girls': '灰姑娘女孩', 'million_live': 'MILLION LIVE!',
    'shiny_colors': 'SHINY COLORS', 'shiny_colors_song': 'SHINY COLORS',
    'idolmaster_kr': '偶像大师KR', 'the_idolmaster_2': '偶像大师2',
    'idolmaster_ofa': '偶像大师 OFA', 'idolmaster_platinum_stars': '偶像大师 白金星光',
    'idolmaster_stella_stage': '偶像大师 星光舞台', 'idolmaster_starlit_season': '偶像大师 星耀季节',
    'im@s': '偶像大师', 'imas': '偶像大师',
    'hololive_production': 'Hololive', 'cover_corporation': 'COVER Corp.',
    'hololive_0th_gen': 'Hololive 0期生', 'hololive_1st_gen': 'Hololive 1期生',
    'hololive_2nd_gen': 'Hololive 2期生', 'hololive_gamers_group': 'Hololive Gamers',
    'hololive_3rd_gen': 'Hololive 3期生', 'hololive_4th_gen': 'Hololive 4期生',
    'hololive_5th_gen': 'Hololive 5期生', 'hololive_6th_gen': 'Hololive 6期生',
    'hololive_indonesia': 'Hololive Indonesia', 'hololive_id_gen1': 'Hololive ID 1期生',
    'hololive_id_gen2': 'Hololive ID 2期生', 'hololive_id_gen3': 'Hololive ID 3期生',
    'hololive_english': 'Hololive English', 'hololive_en_myth': 'Hololive EN Myth',
    'hololive_en_council': 'Hololive EN Council', 'hololive_en_advent': 'Hololive EN Advent',
    'hololive_dev_is': 'hololive DEV_IS', 're_gloss': 'ReGLOSS',
    'flow_glow': 'FLOW GLOW', 'suisei_music': '星街音乐', 'holo_alt': 'Hololive Alternative',
    'holo_gra': 'Hololive小剧场', 'holo_no_grafiti': 'Hololive小剧场',
    'fake_type': 'Fake Type.', 'holo_error': 'hololive ERROR',
    'sakura_miko': '樱巫女', 'shirakami_fubuki': '白上吹雪', 'natsuiro_matsuri': '夏色祭',
    'akai_haato': '赤井心', 'usada_pekora': '兔田佩克拉', 'hoshimachi_suisei': '星街彗星',
    'tokino_sora': '时乃空', 'roboco': '萝卜子', 'yozora_mel': '夜空梅露',
    'aki_rosenthal': '亚绮·罗森塔尔', 'minato_aqua': '凑阿库娅', 'murasaki_shion': '紫咲诗音',
    'nakiri_ayame': '百鬼绫目', 'yuzuki_choco': '癒月巧可', 'oozora_subaru': '大空昴',
    'ookami_mio': '大神澪', 'nekomata_okayu': '猫又小粥', 'inugami_korone': '戌神沁音',
    'shiranui_flare': '不知火芙蕾雅', 'shirogane_noel': '白银诺艾尔', 'houshou_marine': '宝钟玛琳',
    'tsunomaki_watame': '角卷绵芽', 'tokoyami_towa': '常暗永远', 'himemori_luna': '姬森璐娜',
    'yukihana_lamy': '雪花菈米', 'momosuzu_nene': '桃铃音音', 'shishiro_botan': '狮白牡丹',
    'omarun_polka': '尾丸波尔卡', 'laplus_darkness': '拉普拉斯·达克尼斯', 'takane_lui': '鹰岭露依',
    'hakui_koyori': '博衣小夜璃', 'sakamata_chloe': '沙花叉克罗耶', 'kazama_iroha': '风真伊吕波',
    'ayunda_risu': '阿云妲·丽丝', 'moona_hoshinova': '穆娜·霍星诺瓦', 'airani_iofifteen': '艾拉尼·伊欧菲芙婷',
    'kureiji_ollie': '克蕾伊吉·奥莉', 'anya_melfissa': '阿妮娅·梅尔菲萨', 'pavolia_reine': '帕沃莉亚·蕾恩',
    'vestia_zeta': '维斯蒂亚·泽塔', 'kaela_kovalskia': '卡埃拉·科瓦尔斯基亚', 'kobo_kanaeru': '可波·卡娜艾露',
    'mori_calliope': '森美声', 'takanashi_kiara': '小鸟游琪亚拉', 'ninomae_ina\'nis': '一伊那尔栖',
    'gawr_gura': '噶呜·古拉', 'watson_amelia': '华生·阿米莉亚', 'irys': 'Irys',
    'ceres_fauna': '塞莱斯·法乌娜', 'ouro_kronii': '奥罗·克罗尼', 'nanashi_mumei': '七诗无铭',
    'hakos_baelz': '哈科斯·贝尔丝', 'shiori_novella': '诗织·诺薇拉', 'koseki_bijou': '古石碧珠',
    'nerissa_ravenous': '娜莉莎·雷文克洛丝', 'fuwawa_abyssgard': '芙瓦瓦·深渊守护者',
    'mococo_abyssgard': '摩可可·深渊守护者', 'elizabeth_rose_bloodflame': '伊丽莎白·玫瑰·血焰',
    'gigi_murin': '琪琪·村玲', 'cecilia_immergreen': '塞西莉亚·永恒绿', 'raora_panthera': '劳拉·潘瑟拉',
    'hololive_0期生': 'Hololive 0期生', 'hololive_1期生': 'Hololive 1期生',
    'hololive_2期生': 'Hololive 2期生', 'hololive_3期生': 'Hololive 3期生',
    'hololive_4期生': 'Hololive 4期生', 'hololive_5期生': 'Hololive 5期生',
    'hololive_6期生': 'Hololive 6期生', 'hololive_EN': 'Hololive EN',
    'hololive_ID': 'Hololive ID', 'Holoearth': 'Holoearth',
    'blue_protocol': '蓝色协议', 'gbf': '碧蓝幻想', 'grandblue': '碧蓝幻想',
    'uma_musume': '赛马娘', 'uma_musume_pretty_derby': '赛马娘 Pretty Derby',
    '赛马娘_pretty_derby': '赛马娘 Pretty Derby', 'pripara': 'Pripara',
    'aikatsu_planet': '偶像活动Planet！', 'aikatsu_friends': '偶像活动Friends',
    'aikatsu_stars': '偶像活动Stars！', 'aikatsu_on_parade': '偶像活动 on Parade！',
    'aikatsu_academy': '偶像活动学园', 'pretty_rhythm_rainbow_live': '美妙旋律 Rainbow Live',
    'pretty_rhythm_dear_my_future': '美妙旋律 Dear My Future', 'pretty_rhythm_aurora_dream': '美妙旋律 Aurora Dream',
    'pripara_idol_time': '偶像时间Pripara', 'pripara_movie': 'Pripara 电影',
    'kiratto_prichan': '闪亮亮☆美妙频道', 'waccha_primagi': '哇恰美妙魔法！',
    'himitsu_no_aipri_anime': '秘密的爱噗哩', 'idolland_pripara': '偶像乐园Pripara',
    'pripara_series': 'Pripara系列', 'pretty_series_anime': 'Pretty系列',
    'aikatsu_series': '偶像活动系列', 'mermaid_melody': '人鱼的旋律',
    'lilpri': '变身！公主偶像', 'jewelpet': '宝石宠物', 'onegai_my_melody_series': '拜托了我的旋律',
    'jewelpet_kira_deco': '宝石宠物 Kira☆Deco！',
    'jewelpet_happiness': '宝石宠物 Happiness', 'jewelpet_lady': 'Lady 宝石宠物',
    'jewelpet_sunshine': '宝石宠物 Sunshine', 'jewelpet_twinkle': '宝石宠物 Twinkle☆',
    'jewelpet_magical_change': '宝石宠物 Magical Change', 'jewelpet_attack_chance': '宝石宠物 Attack Chance!?',
    'rilakkuma': '轻松小熊', 'sumikko_gurashi': '角落生物', 'sanrio_characters': '三丽鸥',
    'san-x_characters': 'San-X', 'kamen_rider_revice': '假面骑士Revice',
    'kamen_rider_geats': '假面骑士Geats', 'kamen_rider_gotchard': '假面骑士Gotchard',
    'kamen_rider_gavv': '假面骑士Gavv', 'revi': 'Revi', 'vice': 'Vice',
    'geats': '假面骑士Geats', 'gotchard': '假面骑士Gotchard', 'zero_one': '假面骑士Zero-One',
    'saber': '假面骑士Saber', 'zi_o': '假面骑士Zi-O', 'build': '假面骑士Build',
    'ex_aid': '假面骑士Ex-Aid', 'ghost': '假面骑士Ghost', 'drive': '假面骑士Drive',
    'gaim': '假面骑士铠武', 'wizard': '假面骑士Wizard', 'fourze': '假面骑士Fourze',
    'ooo': '假面骑士OOO', 'w': '假面骑士W', 'decade': '假面骑士Decade',
    'kiva': '假面骑士Kiva', 'den_o': '假面骑士电王', 'kabuto': '假面骑士Kabuto',
    'hibiki': '假面骑士响鬼', 'blade': '假面骑士Blade', 'faiz': '假面骑士555',
    'ryuki': '假面骑士龙骑', 'agito': '假面骑士Agito', 'kuuga': '假面骑士空我',
    'super_sentai_series': '超级战队', 'avatar_sentai_donbrothers': '暴太郎战队Donbrothers',
    'ohsama_sentai_king_ohger': '王样战队君王者', 'bakuage_sentai_boonboomger': '爆上战队BoonBoomger',
    'no1_sentai_gozyuger': '第一战队豪兽者', 'king_ohger': '君王者',
    'donbrothers': 'Donbrothers', 'boonboomger': 'BoonBoomger',
    'ultraman_trigger': '特利迦奥特曼', 'ultraman_decker': '德凯奥特曼',
    'ultraman_blazar': '布莱泽奥特曼', 'ultraman_arc': '亚刻奥特曼',
    'ultraman_taiga': '泰迦奥特曼', 'ultraman_z': '泽塔奥特曼',
    'shin_ultraman_movie': '新·奥特曼', 'ultraman_rising': 'Ultraman: Rising',
    'ultra_series': '奥特曼系列', 'unfortunately': '残念ながら',
    'assassination_classroom': '暗杀教室', 'ansatsu_kyoushitsu': '暗杀教室',
    'saiki_kusuo': '齐木楠雄的灾难', 'saiki_k': '齐木楠雄的灾难',
    'sakamoto_days_anime': '坂本日常', 'dandadan_anime': '胆大党',
    'kaiju_no_8_anime': '怪兽8号', 'kaiju_no_8_anime_2024': '怪兽8号',
    'spy_x_family_movie': '间谍过家家 剧场版', 'spy_x_family_code_white': '间谍过家家 CODE: White',
    'spy_family_season2': '间谍过家家 第二季',
    'blue_exorcist_shimane': '青之驱魔师 岛根启明结社篇',
    'blue_exorcist_yukio': '青之驱魔师 雪之果篇', 'ao_ex': '青之驱魔师',
    'black_clover_movie': '黑色五叶草 魔法帝之剑',
    'boku_no_hero': '我的英雄学院', 'my_hero_academia_season7': '我的英雄学院 第七季',
    'mha': '我的英雄学院', 'bnha': '我的英雄学院',
    'mashle_season2': '物理魔法使马修 第二季', 'mashle_anime': '物理魔法使马修',
    'tower_of_god_anime': '神之塔', 'tower_of_god_2': '神之塔 第二季',
    'wind_breaker_s2': '防风铃 第二季', 'wb': '防风铃',
    'ron_kamonohashi': '鸭乃桥论的禁忌推理', 'kamonohashi': '鸭乃桥论的禁忌推理',
    'ojiisan': '老爹', 'fairytail_100yq': '妖精的尾巴 百年任务',
    'fairy_tail_100_years_quest': '妖精的尾巴 百年任务',

    # 偶像/音乐
    'monster_girl_quest': '魔物娘Quest',
    'splatoon_2': '喷射战士2', 'splatoon_3': '喷射战士3',
    'final_fantasy_series': '最终幻想系列',
    'sword_art_online': '刀剑神域', 'sword_art_online_anime': '刀剑神域',
    'date_a_live_anime': '约会大作战',
    'vocaloid2': 'VOCALOID2', 'vocaloid3': 'VOCALOID3',
    'vocaloid4': 'VOCALOID4', 'vocaloid5': 'VOCALOID5',
    'tales_of_legendia': '神话传说', 'tales_of_innocence': '纯真传说',
    'tales_of_hearts': '心灵传说', 'tales_of_graces': '圣恩传说',
    'shin_megami_tensei_v_pc': '真女神转生V',
    'persona_5_the_royal': '女神异闻录5 皇家版',
    'darling_in_the_franxx': 'Darling in the Franxx',
    'puss_in_boots:_the_last_wish': '穿靴子的猫2',
    'super_mario_wonder': '超级马力欧 惊奇',
    'super_mario_odyssey': '超级马力欧 奥德赛',
    'super_mario_3d_world': '超级马力欧 3D世界',
    'super_mario_galaxy': '超级马力欧 银河',
    'metroid_prime': '密特罗德 Prime',
    'zelda_echoes_of_wisdom': '塞尔达传说 智慧的再现',
    'genshin_impact_5.0': '原神', 'honkai_star_rail_2.0': '崩坏：星穹铁道',
    'honkai_impact_3rd_part2': '崩坏3',
    'wuthering_waves_1.0': '鸣潮', 'zenless_zone_zero_1.0': '绝区零',
    'blue_archive_2nd': '碧蓝档案', 'blue_archive_3rd': '碧蓝档案',
    'arknights_3rd': '明日方舟', 'arknights_4th': '明日方舟',
    'girls_frontline_2_exilium': '少女前线2：追放',
    'monster_hunter_wilds': '怪物猎人 Wilds', 'monster_hunter_world': '怪物猎人：世界',
    'monster_hunter_rise': '怪物猎人 崛起', 'mhw': '怪物猎人：世界',
    'mh_wilds': '怪物猎人 Wilds', 'mhrise': '怪物猎人 崛起',
    'elden_ring_shadow_of_the_erdtree': '艾尔登法环 黄金树幽影',
    'elden_ring_nightreign': '艾尔登法环 黑夜君临',
    'dark_souls_1': '黑暗之魂', 'dark_souls_2': '黑暗之魂2',
    'dark_souls_3': '黑暗之魂3', 'bloodborne_game': '血源诅咒',
    'sekiro_game': '只狼', 'demons_souls': '恶魔之魂',
    'armored_core_vi': '装甲核心VI', 'ac6': '装甲核心VI',
    'hades_1': '哈迪斯', 'hades_2': '哈迪斯II',
    'dead_cells_game': '死亡细胞', 'hollow_knight_silksong': '空洞骑士：丝之歌',
    'celeste': '蔚蓝', 'ori': '奥日', 'ori_blind_forest': '奥日与黑暗森林',
    'ori_will_of_the_wisps': '奥日与萤火意志', 'cuphead': '茶杯头',
    'hollow_knight_game': '空洞骑士', 'nine_sols': '九日',
    'blasphemous': '渎神', 'blasphemous_2': '渎神2',
    'elder_ring': '艾尔登法环', 'lies_of_p_game': '匹诺曹的谎言',
    'lords_of_the_fallen': '堕落之主', 'remnant_2': '遗迹2',
    'nobody_saves_the_world': '没人拯救世界', 'death_door': '死亡之门',
    'tunic': 'TUNIC', 'hyper_light_drifter': '光明旅者',
    'stellar_blade_ps5': '星刃', 'stellar_blade_ost': '星刃',
    'rise_of_the_ronin': '浪人崛起', 'nioh': '仁王',
    'nioh_2': '仁王2', 'wo_long_fallen_dynasty': '卧龙：苍天陨落',
    'stranger_of_paradise_ffo': '最终幻想 起源', 'ffo': '最终幻想 起源',
    'cyberpunk_2077': '赛博朋克2077', 'phantom_liberty': '赛博朋克2077：往日之影',
    'baldur_gate_3': '博德之门3', 'bg3': '博德之门3',
    'starfield_game': '星空', 'the_outer_worlds': '天外世界',
    'fallout_new_vegas': '辐射：新维加斯', 'fallout_4': '辐射4',
    'elder_scrolls_skyrim': '上古卷轴5：天际', 'skyrim': '上古卷轴5',
    'oblivion': '上古卷轴4：湮灭', 'morrowind': '上古卷轴3：晨风',
    'witcher_3': '巫师3：狂猎', 'witcher_2': '巫师2：国王刺客',
    'the_witcher_3': '巫师3', 'gwint': '昆特牌',
    'cyberpunk_phantom_liberty': '赛博朋克2077：往日之影',
    'assassins_creed_valhalla': '刺客信条：英灵殿',
    'assassins_creed_mirage': '刺客信条：幻景', 'assassins_creed_shadows': '刺客信条：影',
    'ghost_of_tsushima_ps5': '对马岛之鬼', 'ghost_of_yotei': '羊蹄山之鬼',
    'horizon_forbidden_west_burning_shores': '地平线 西之绝境 燃烧海岸',
    'god_of_war_ragnarok_valhalla': '战神 诸神黄昏 英灵殿',
    'spider_man_2': '漫威蜘蛛侠2', 'spider_man_miles_morales': '漫威蜘蛛侠：迈尔斯·莫拉莱斯',
    'wolverine_ps5': '漫威金刚狼', 'marvels_spider_man': '漫威蜘蛛侠',
    'ratchet_clank_rift_apart': '瑞奇与叮当 时空跳转',
    'last_of_us_part2': '最后生还者 第二部', 'the_last_of_us_part_1': '最后生还者 第一部',
    'uncharted_4': '神秘海域4：盗贼末路', 'uncharted_lost_legacy': '神秘海域：失落的遗产',
    'days_gone': '往日不再', 'death_stranding_2': '死亡搁浅2',
    'death_stranding_directors_cut': '死亡搁浅 导演剪辑版',
    'final_fantasy_xvi_dlc': '最终幻想XVI', 'final_fantasy_vii_rebirth': '最终幻想VII 重生',
    'kingdom_hearts_iv': '王国之心IV', 'dragon_quest_xii': '勇者斗恶龙XII',
    'dq12': '勇者斗恶龙XII', 'dq3_hd2d': '勇者斗恶龙III HD-2D',
    'dq1_hd2d': '勇者斗恶龙I HD-2D', 'dq2_hd2d': '勇者斗恶龙II HD-2D',
    'ffix_remake': '最终幻想IX 重制版', 'fft_remaster': '最终幻想战略版 重制版',
    'chrono_trigger_remaster': '时空之轮 重制版', 'chrono_cross_remaster': '穿越时空 重制版',
    'live_a_live': '时空勇士', 'octopath_traveler_2': '八方旅人II',
    'octopath_2': '八方旅人II', 'triangle_strategy': '三角战略',
    'dragon_quest_monsters_3': '勇者斗恶龙 怪兽篇3',
    'dragon_quest_treasures_switch': '勇者斗恶龙 寻宝探险团',
    'dragon_quest_builders_2': '勇者斗恶龙 创世小玩家2',
    'infinity_strash_dragon_quest': '勇者斗恶龙 达伊的大冒险',
    'star_ocean_the_second_story_r': '星之海洋2 第二个故事R',
    'star_ocean_6': '星之海洋6', 'star_ocean_5': '星之海洋5',
    'star_ocean_4': '星之海洋4', 'star_ocean_3': '星之海洋3',
    'star_ocean_2': '星之海洋2', 'star_ocean_1': '星之海洋',
    'valkyrie_elysium': '北欧女神 极乐世界', 'valkyrie_profile_lenneth': '北欧女神 蕾娜丝',
    'vp_lenneth': '北欧女神 蕾娜丝', 'vp_silmeria': '北欧女神2 希尔梅莉亚',
    'vp_covenant': '北欧女神 负罪者', 'tactics_ogre_reborn': '皇家骑士团 重生',
    'final_fantasy_tactics_remaster': '最终幻想战略版 重制版',
    'front_mission_1st': '前线任务 1st', 'front_mission_2': '前线任务2',
    'front_mission_3': '前线任务3', 'triangle_strategy_pc': '三角战略',
    'diofield_chronicle': '神领编年史', 'disgaea_7': '魔界战记7',
    'disgaea_6': '魔界战记6', 'disgaea_5': '魔界战记5',
    'disgaea_4': '魔界战记4', 'disgaea_3': '魔界战记3',
    'disgaea_2': '魔界战记2', 'disgaea_1': '魔界战记',
    'makai_senki_disgaea': '魔界战记', 'phantom_brave_lost_hero': '灵武战记 失落英雄',
    'phantom_brave_game': '灵武战记', 'soul_nomad': '灵魂摇篮',
    'makai_kingdom': '魔界王国', 'la_pucelle_tactics': '光之圣女',
    'rhapsody': '狂想曲', 'rhapsody_2': '狂想曲2',
    'rhapsody_3': '狂想曲3', 'ni_no_kuni': '二之国',
    'ni_no_kuni_2': '二之国II', 'yokai_watch_4': '妖怪手表4',
    'fantasy_life': '幻想生活', 'fantasy_life_i': '幻想生活i',
    'snack_world': '点心世界', 'layton': '雷顿教授',
    'layton_mystery_journey': '雷顿神秘之旅', 'inazuma_eleven': '闪电十一人',
    'inazuma_eleven_ares': '闪电十一人 阿瑞斯的天秤', 'danball_senki': '纸箱战机',
    'megaton_musashi': '百万吨级武藏', 'yo_kai_watch': '妖怪手表',
    'shin_chan': '蜡笔小新', 'shin_chan_games': '蜡笔小新',
    'doraemon_games': '哆啦A梦', 'doraemon_nobita': '哆啦A梦',
    'crayon_shinchan': '蜡笔小新', 'shinchan_summer': '蜡笔小新 我与博士的暑假',
    'summer_vacation': '我的暑假', 'boku_no_natsuyasumi': '我的暑假',
    'attack_on_titan': '进击的巨人', 'aot': '进击的巨人',
    'shingeki_no_kyojin_anime': '进击的巨人',
    'manga': '漫画', 'anime': '动画', 'game': '游戏',
    'vn': '视觉小说', 'light_novel': '轻小说', 'ln': '轻小说',
    'movie': '电影', 'tv': '电视剧', 'webtoon': '网络漫画',
    'manhwa': '韩国漫画', 'manhua': '中国漫画', 'donghua': '中国动画',
    'tokusatsu': '特摄', 'indie_game': '独立游戏', 'doujin': '同人',
    'original': '原创', 'oc': '原创角色', 'fan_art': '同人',
    'monster_girl_encyclopedia_world': '魔物娘图鉴世界',
    'mge': '魔物娘图鉴', 'mgq': '魔物娘Quest',
}

print(f"映射表: {len(SOURCE_MAP)} 条")

with open(SRC, 'r') as f:
    data = json.load(f)

people = data['character']
charsort = data['charsort']

# 1. Source汉化
src_changes = 0
for cname, info in people.items():
    old = str(info.get('Source', ''))
    if old in SOURCE_MAP and SOURCE_MAP[old] != old:
        info['Source'] = SOURCE_MAP[old]
        src_changes += 1

# 2. charsort系列key汉化
new_charsort = {}
for series, chars in charsort.items():
    new_series = SOURCE_MAP.get(series, series)
    if new_series in new_charsort:
        new_charsort[new_series].extend(chars)
    else:
        new_charsort[new_series] = list(chars)
data['charsort'] = new_charsort

# 3. cname清理：移除"角色"前缀
new_people = {}
for old_cn, info in list(people.items()):
    new_cn = old_cn
    if new_cn.startswith('角色'):
        new_cn = new_cn[2:]
    if new_cn in new_people:
        cnt = 1
        while f"{new_cn}_{cnt}" in new_people:
            cnt += 1
        new_cn = f"{new_cn}_{cnt}"
    new_people[new_cn] = info
data['character'] = new_people

# 4. charsort角色key更新
old_to_new = {}
for old_cn, new_cn in zip(people.keys(), new_people.keys()):
    if old_cn != new_cn:
        old_to_new[old_cn] = new_cn
for series, chars in new_charsort.items():
    for i, ch in enumerate(chars):
        if ch in old_to_new:
            chars[i] = old_to_new[ch]

# 备份+保存
import shutil, time
bak = SRC.replace('.json', f'_backup_{int(time.time())}.json')
shutil.copy2(SRC, bak)
with open(SRC, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# 统计
import re
pf = data['character']
cn_f = sum(1 for c in pf if re.search(r'[a-zA-Z\u3040-\u309F\u30A0-\u30FF]', c))
src_e = sum(1 for i in pf.values() if re.search(r'[a-zA-Z]', str(i.get('Source',''))))
print(f"备份: {bak}")
print(f"Source汉化: {src_changes}")
print(f"总角色: {len(pf)}, cname含外文: {cn_f}, Source含EN: {src_e}")